aws-amplify/amplify-codegen-ui

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/__tests__/studio-ui-json/iconBug.json, packages/codegen-ui-react/lib/amplify-ui-renderers/amplify-renderer.ts
**Wait until after initial release to merge change.**
Built-in iconset components require the component type to be mapped to pascal calse. A new object was created in amplify-renderer to map the component type. This resulted in the [object equality comparison in studio-node](https://github.com/aws-amplify/amplify-codegen-ui/blob/4c82035c41b2ff015126e0f2751e616b5b7761fd/packages/codegen-ui/lib/frontend-manager-node.ts#L46) to fail because the objects were different references.
=> fix: use correct override index for built-in iconset components

CHANGELOG.md, CONTRIBUTING.md, lerna.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
Release addressing a few bugs identified in the launch lead-up which weren't deemed blocking.
=> chore(release): v1.1.0

.github/workflows/release.yml, CONTRIBUTING.md
It is a little difficult to fully test this without publishing to NPM. We could make a fake release to fully test it out if we want to. I did confirm that `lerna publish from-git -y` will not publish if the HEAD commit does not have a tag so there is limited risk of accidentaly publishing.
=> ci: automate npm release

.circleci/config.yml, .github/workflows/check.yml
Style and unit test jobs have been removed from GitHub Actions and moved to circle ci. I'll update the required checks when we are ready to merge.
=> ci: move style and unit test jobs to circle ci

.circleci/config.yml, .github/workflows/release.yml
* Move npm publish job from github actions to circleci
* publish job only runs on main branch
* If commit matches release commit style create a full release, else no-op
* circle ci cannot conditional run jobs based on the commit message unfortunately
* In the future we will add a pre-release to the else condition
=> ci: move npm publish job to circle ci

.circleci/config.yml, .circleci/publish.sh, CONTRIBUTING.md, package.json
Merging to main so that tagged releases can be created off of main.
See CONTRIBUTING.md for instructions on how to create a tagged release.
NPM publishing via circle CI now works for prod release, pre-release, and tagged release. 
Successful publish [here](https://app.circleci.com/pipelines/github/aws-amplify/amplify-codegen-ui/111/workflows/b60bd4d9-0669-4465-a203-0b46964233c4/jobs/447).
=> ci: add tagged release

.github/workflows/check.yml, scripts/integ-setup.bat, scripts/integ-setup.sh
Create React App release a new version 5.0.0 this morning: https://github.com/facebook/create-react-app/releases/tag/v5.0.0
The new version of Create React App upgrades to Webpack 5. There is an existing [issue with Webpack 5 and graphql](https://github.com/graphql/graphql-js/issues/2721) that is causing newly created CRA apps to fail compilation.
This change will pin the react-scripts to 4.0.3 so that Webpack 4 is still used.
=> ci: pin react-scripts@4.0.3

.circleci/publish.sh, CONTRIBUTING.md
No longer use the [canary option](https://github.com/lerna/lerna/tree/main/commands/publish#--canary) because [it is broken](https://github.com/lerna/lerna/issues/2622). 
Now manually create a pre-release version number and then use `lerna publish from-git`.
Other changes:
* Will always publish a new pre-release (even if there are no changes to source).
* Change pre-release `alpha` preid to short commit hash.
* Use tagged release name as dist tag 
* Add short commit hash to tagged release preid.
Tested locally when unauthenticated.
```
> export CIRCLE_BRANCH = test-pre-relase
> bash -x .circleci/publish.sh 
++ git log --format=%s -n 1
+ [[ feat: something =~ ^chore\(release\): v.* ]]
++ echo adc94308d775618e29c84a8fbd2380bb5dfd181b
++ cut -c -7
+ SHORT_SHA1=adc9430
+ [[ fix-prerelease =~ …
```
=> ci: fix pre-release and tagged release

packages/codegen-ui-react/lib/__tests__/__snapshots__/react-studio-template-renderer-helper.test.ts.snap, packages/codegen-ui-react/lib/__tests__/react-studio-template-renderer-helper.test.ts, packages/codegen-ui-react/lib/react-studio-template-renderer-helper.ts, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json
Move prettier to optional dependency: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#optionaldependencies
If prettier is not installed, do not run `prettier.format` on generated code.
We could also expose an option (something like `formatGeneratedCode`) and throw an error if `formatGeneratedCode` is `true` and prettier is not installed.
=> feat: make prettier an optional dependency

packages/codegen-ui-react/lib/__tests__/__snapshots__/react-component-render-helper.test.ts.snap, packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/react-component-render-helper.test.ts, packages/codegen-ui-react/lib/__tests__/studio-ui-json/buttonGolden.json, packages/codegen-ui-react/lib/react-component-render-helper.ts
JS types specified in the type prop is in lowercase, and all of the values pulled from the backend are string literals. Updating the function to take those into account
=> fix: proper use of type from ui builder backend

packages/codegen-ui-react/lib/__tests__/__snapshots__/react-index-studio-template-renderer.test.ts.snap, packages/codegen-ui-react/lib/__tests__/react-index-studio-template-renderer.test.ts, packages/codegen-ui-react/lib/react-index-studio-template-renderer.ts
Also removed unreachable code because declarations are never produced for the index file.
=> test: add unit tests to react index renderer

packages/codegen-ui-react/lib/__tests__/__snapshots__/react-studio-template-renderer-helper.test.ts.snap, packages/codegen-ui-react/lib/__tests__/react-studio-template-renderer-helper.test.ts, packages/codegen-ui-react/lib/react-studio-template-renderer-helper.ts
Swallowing prettier errors resulted in code not being formatted in cases where the generated code had invalid syntax. I'm not aware any occurrence in production yet.
The error will now bubble up if prettier fails to format.
=> fix: do not swallow prettier.format errors

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/react-render-config.ts, packages/codegen-ui-react/lib/react-studio-template-renderer-helper.ts
Add option to react render config to enable inline source map with inline sources. See snapshot for example of inline source map. `//# sourceMappingURL=data:...`
I set `inlineSourceMap` to also enable `inlineSources` so that the TypeScript sources would also be available. We don't have a use case where it would make sense to have `inlineSourceMap` true, but `inlineSources` be false because we do not output the sources in another way. 
I will need to verify with the ui builder team that this solution works for them.
=> feat: add option to render inline source map

.github/workflows/beta-canary.yml, .github/workflows/latest-canary.yml
Adding a schedule-based set of workflows which will test basic smoketest functionality against the current `beta` and `latest` releases of CLI, to help us tease out issues caused by transient dependencies before customers need to raise an issue.
=> feat: add canary for CLI Codegen UI functionality against beta and latest tags

packages/codegen-ui-react/lib/__tests__/__snapshots__/react-component-render-helper.test.ts.snap, packages/codegen-ui-react/lib/__tests__/react-component-render-helper.test.ts, packages/codegen-ui-react/lib/react-component-render-helper.ts, packages/codegen-ui/lib/types/studio-types.ts
* Added operandType in ConditionalStudioComponentProperty
* Parsing string values of operand to match type with operandType
* Non-breaking change. Backwards-compatible with previous behavior (treated value as string)
=> fix: added operand type to ConditionalStudioComponentProperty

packages/codegen-ui-react/package-lock.json, packages/codegen-ui/package-lock.json, packages/test-generator/package-lock.json
=> chore: upgrade to follow-redirects@1.14.7

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/amplify-ui-renderers/collection.ts, packages/codegen-ui-react/lib/react-component-renderer.ts, packages/codegen-ui-react/lib/react-component-with-children-renderer.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui/lib/__tests__/studio-node.test.ts, packages/codegen-ui/lib/studio-node.ts, packages/test-generator/integration-test-templates/cypress/integration/generated-components-spec.ts, packages/test-generator/integration-test-templates/src/ComponentTests.tsx
N/A
Replace the use of existing getOverrideProps with calls to an injected overrItems callback provided by the user. This allows the user to access item and index information in their overrides.
This is the first of two major updates to overrides which we'll be rolling out.
=> feat: adding support for  prop on collection components

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-json/componentWithUserSpecificAttributes.json, packages/codegen-ui-react/lib/react-component-render-helper.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui/lib/__tests__/renderer-helper.test.ts, packages/codegen-ui/lib/renderer-helper.ts, packages/codegen-ui/lib/types/studio-types.ts
Moving auth attribute usage to child components to avoid creating top-level auth statement.
=> feat: implement auth attributes directly at the child level

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/react-component-render-helper.ts, packages/codegen-ui-react/lib/react-component-renderer.ts, packages/codegen-ui-react/lib/react-component-with-children-renderer.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui-react/lib/workflow/action.ts, packages/codegen-ui-react/lib/workflow/events.ts, packages/codegen-ui-react/lib/workflow/index.ts
If you have any suggestions on how the unique identifier should be constructed please leave a comment. I just went with one structure I though was sensible.
I needed to move some functions to a new file to avoid a cyclical dependency between `action.ts` and `react-component-render-helper.ts`.
=> feat: use unique identifier for actions

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/workflow/events.ts
N/A
We're planning to return the function directly from the ui helpers, so getting rid of the `run` parameter which was being returned, and invoking directly.
=> chore: remove run from action bindings per golden updates

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/imports/import-mapping.ts, packages/test-generator/integration-test-templates/cypress/integration/generate-spec.ts, packages/test-generator/integration-test-templates/src/WorkflowTests.tsx, packages/test-generator/integration-test-templates/src/mock-helpers.js, packages/test-generator/lib/components/workflow/dataStoreActions.json, packages/test-generator/lib/components/workflow/formWithState.json, packages/test-generator/lib/components/workflow/index.ts
N/A
Setting up e2e tests for the new actions. These are still wip, but I'd like to get them committed, and un-skipped as the hooks become available.
=> chore: add datastore e2e tests

packages/test-generator/integration-test-templates/cypress/integration/workflow-spec.ts, packages/test-generator/integration-test-templates/src/WorkflowTests.tsx, packages/test-generator/integration-test-templates/src/mock-helpers.js, packages/test-generator/lib/components/workflow/formWithState.json
N/A
Now that we have a mock to use for testing, enabling the datastore related action tests. Outstanding action is to remove the stubs and flip back to ui once released.
=> chore: add running datastore tests using current stubs from ui

package-lock.json, packages/codegen-ui-react/package-lock.json, packages/codegen-ui/package-lock.json
- chore: upgrade to node-fetch@2.6.7
- chore: upgrade to trim-off-newlines@1.0.3
- chore: upgrade to nanoid@3.1.31
=> chore: resolve dependabot warnings

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/primitive.ts, packages/codegen-ui-react/lib/react-component-renderer.ts, packages/codegen-ui-react/lib/react-component-with-children-renderer.ts, packages/codegen-ui-react/lib/workflow/events.ts, packages/codegen-ui-react/lib/workflow/mutation.ts, packages/codegen-ui/example-schemas/workflow/stepperControlledElement.json
N/A
Stepper primitive takes an onStepChange callback, rather than onChange, and issues a raw number rather than a full SyntheticEvent, adding support for synthetic event names, as well as implementations which are based on the primitive type.
Also updated the SliderField to use the numeric callback, though w/ the name onChange per UI docs.
=> fix: add override for stepper and slider controlled change events

packages/codegen-ui-react/lib/__tests__/workflow/__snapshots__/mutation.test.ts.snap, packages/codegen-ui-react/lib/__tests__/workflow/mutation.test.ts, packages/codegen-ui-react/lib/workflow/mutation.ts
getComponentFromComponentTree would fail for grandchild case. The `.find` would cause the parent of the grand child to be returned in place because `.find`. Change this to a map and then find on the mapped values fixes this.
=> fix: get grand child from component tree

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/primitive.ts, packages/codegen-ui-react/lib/workflow/mutation.ts
Set default initial state value for form components. 
List was determined by interacting with TwoWayBinding tests on integration app and adding default initial values for components that gave a warning.
Todo in another change:
If a `defaultValue` is set by the customer and the component becomes controlled the defaultValue needs to be removed because the form components cannot have both `defaultValue` and `value`.
=> feat: add default initial value for form component state

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/__tests__/workflow/action.test.ts, packages/codegen-ui-react/lib/workflow/action.ts, packages/codegen-ui/example-schemas/workflow/invalidNameForMethod.json
N/A
Adding a `sanitizeName` method, which will scrub the component name to ensure we are able to generate valid statement declarations for action and mutations.
=> fix: sanitize component name before generating statement declarations

packages/test-generator/integration-test-templates/cypress/integration/action-binding-spec.ts, packages/test-generator/integration-test-templates/cypress/integration/generate-spec.ts, packages/test-generator/integration-test-templates/src/ActionBindingTests.tsx, packages/test-generator/integration-test-templates/src/App.tsx, packages/test-generator/lib/components/workflow/dataStoreActionBindings.json, packages/test-generator/lib/components/workflow/index.ts, packages/test-generator/lib/components/workflow/mutationActionBindings.json
N/A
Adding e2e tests to verify functionality of all binding types feeding into mutation and updateDataStore actions.
=> chore: adding mutation binding tests

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/react-component-with-children-renderer.ts, packages/codegen-ui-react/lib/react-index-studio-template-renderer.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui-react/lib/react-theme-studio-template-renderer.ts, packages/codegen-ui-react/lib/workflow/mutation.ts, packages/codegen-ui/lib/__tests__/__utils__/mock-classes.ts, packages/codegen-ui/lib/common-component-renderer.ts, packages/codegen-ui/lib/studio-template-renderer.ts
In the case that a component becomes controlled due to state reference, but the customer has added a `defaultValue` prop the `defaultValue` prop should be removed to avoid react warnings.
This change modified the order of some functions so the import order has changed as a result.
=> fix: remove defaultValue if value is added to component

packages/test-generator/integration-test-templates/cypress/integration/action-binding-spec.ts, packages/test-generator/integration-test-templates/cypress/integration/generated-components-spec.ts, packages/test-generator/integration-test-templates/src/ActionBindingTests.tsx, packages/test-generator/integration-test-templates/src/App.tsx, packages/test-generator/integration-test-templates/src/ComponentTests.tsx, packages/test-generator/integration-test-templates/src/mock-utils.ts
N/A
* Create auth utils to allow injection of authenticated user data into local storage (mock what the real Authentication category does).
* Add e2e tests for auth behavior.
=> chore: backfill e2e tests for auth bindings, add auth mock utils

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/react-component-render-helper.ts, packages/codegen-ui-react/lib/workflow/action.ts, packages/codegen-ui/example-schemas/workflow/mutationWithUnsanitizedTarget.json, scripts/integ-setup.sh
N/A
Bug discovered if mutation target has an invalid name, i.e. the comp name is `T-Shirt Label` we'd try to generate a method `const T-Shirt Labellabelclick = use<Blah>` which is invalid. Scrubbing the name for special characters first.
=> fix: support mutation targets with invalid js names

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/__tests__/workflow/__snapshots__/mutation.test.ts.snap, packages/codegen-ui-react/lib/__tests__/workflow/mutation.test.ts, packages/codegen-ui-react/lib/imports/import-mapping.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui-react/lib/workflow/mutation.ts, packages/codegen-ui/example-schemas/workflow/initialValueBindings.json, packages/codegen-ui/lib/__tests__/utils/component-metadata.test.ts, packages/codegen-ui/lib/__tests__/utils/state-reference-metadata.test.ts, packages/codegen-ui/lib/utils/component-metadata.ts, packages/codegen-ui/lib/utils/index.ts, packages/codegen-ui/lib/utils/state-reference-metadata.ts, packages/test-generator/integration-test-templates/cypress/integration/action-binding-spec.ts, packages/test-generator/integration-test-templates/src/ActionBindingTests.tsx, packages/test-generator/lib/components/workflow/initialValueBindings.json, scripts/integ-setup.bat
N/A
* Add support for useEffect to update dependent state values once useData or useAuth values have settled.
* Still needs unit tests.
* Still needs improved E2E verification
* Still likely needs to determine how we keep from mutations and state values waffling a bound state element back and forth. (I'd propose we initialize these to `undefined` and then only set the value if the depenedencies are all non-null, and the value itself isn't yet set).
=> feat: poc for useEffect to manage state dependencies

packages/codegen-ui-react/lib/react-component-render-helper.ts
N/A
Studio UI transpiles to ES2015, and replaceAll isn't supported, replacing w/ a global replace.
=> fix: don't use replaceAll since it's not supported in ES2015

packages/codegen-ui-react/lib/react-required-dependency-provider.ts
N/A
We'll likely need to bump a patch version once this is fixed and resolved, but https://github.com/aws-amplify/amplify-ui/issues/1396, but we definitely won't be on 3.0.0 anymore.
=> chore: downgrade ui-react dep since they're no longer MV bumping

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/keywords.ts, packages/codegen-ui-react/lib/react-component-render-helper.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui/example-schemas/bindings/data/dataBindingNamedClass.json, packages/test-generator/integration-test-templates/cypress/integration/generate-spec.ts, packages/test-generator/integration-test-templates/cypress/integration/generated-components-spec.ts, packages/test-generator/integration-test-templates/src/ComponentTests.tsx, packages/test-generator/integration-test-templates/src/models/index.d.ts, packages/test-generator/integration-test-templates/src/models/schema.js, packages/test-generator/lib/components/bindings/data/dataBindingNamedClass.json, packages/test-generator/lib/components/bindings/data/index.ts, packages/test-generator/lib/components/bindings/index.ts, packages/test-generator/lib/components/index.ts
N/A
For full list of reserved keywords, refer to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#keywords
=> fix: address reserved keywords in bindings

scripts/integ-setup.sh
CRA automatically installs the latest version of TypeScript (4.6.2). This out of the supported range of codegen (~4.4.4) and caused an error with ScriptTarget. I'm not sure yet what the exact error is but this will resolve the issue until codegen needs to upgrade.
=> test: pin typescript to 4.4.4 for integration tests

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/react-component-render-helper.test.ts, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/react-component-render-helper.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui-react/package-lock.json, packages/codegen-ui/example-schemas/bindings/data/dataBindingWithSameNameAsComponent.json, packages/codegen-ui/package-lock.json, packages/test-generator/integration-test-templates/cypress/integration/generate-spec.ts, packages/test-generator/integration-test-templates/cypress/integration/generated-components-spec.ts, packages/test-generator/integration-test-templates/src/ComponentTests.tsx, packages/test-generator/lib/components/bindings/data/User.json, packages/test-generator/lib/components/bindings/data/index.ts, packages/test-generator/package-lock.json
Today, if you have a component which has the same name in Figma as your data model does, you'll end up w/ a validation error, since you're importing a class that has the same top-level name as your component. This change mitigates that by exporting the default function aliased with an int if necessary (i.e. MyComponent0). This shouldn't impact the end user, since they will be importing from the `index.js` file instead, which just uses the correct name.
=> fix: export aliased component name on data model collision

CHANGELOG.md, lerna.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
- fix: revert export aliased component name on data model collision
- chore(release): v2.1.2
=> new release

.github/workflows/check.yml
We had a separate account which we were using for testing. Flipping back to the standard app secrets.
=> chore: flip back to integ test secrets instead of temp release secrets

packages/test-generator/integration-test-templates/cypress/integration/complex-spec.ts, packages/test-generator/integration-test-templates/cypress/integration/primitives-spec.ts
Issue #, if available:
**Problem**
Complex integ tests were failing due to the element styles being applied in a different order than previously.
**Solution**
Because the order of the styles do not matter to functionality, the tests are now made to be indifferent to it.
Alternative considered
Q: Why did you not just use e.g. `cy.get(#element).should('have.css', 'color', 'blue')`?
A: I found that it was not reliable because the styles that codegen applies to a given element is sometimes shown as overridden by the parent with this approach.
=> fix: make complex integ tests agnostic to style order

CHANGELOG.md, lerna.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
- Rename the “.jsx.d.ts” files to just “.d.ts” file in order for VS code to give Intellisense
- Support type casting in DataStore hooks
=> chore(release): v2.2.0

packages/codegen-ui/lib/types/bindings.ts
* Renaming Slot to Amplify.Slot to follow the latest naming convention
=> fix: rename Slot to Amplify.Slot

packages/codegen-ui/index.ts, packages/codegen-ui/lib/__tests__/__utils__/mock-schemas.ts, packages/codegen-ui/lib/__tests__/generic-from-datastore.test.ts, packages/codegen-ui/lib/generate-form-definition/form-to-component.ts, packages/codegen-ui/lib/generate-form-definition/helpers/field-type-map.ts, packages/codegen-ui/lib/generic-from-datastore.ts, packages/codegen-ui/lib/types/data.ts
Codegen will use `GenericDataSchema` to interface with customer data models when mapping forms.
This PR
- adds the `GenericDataSchema` to types
- adds a util that maps DataStore `Schema` to `GenericDataSchema`
=> chore: add util to map datastore schema to generic

packages/codegen-ui/lib/__tests__/generate-form-definition/generate-form-definition.test.ts, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/datastore-model.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/datastore-model.ts
For forms generated by data model, we do not want to generate fields that are auto-generated read only (such as createdBy or updatedBy).  We also do not want to generate a field for the ID field that is auto generated for every model.
=> chore: skip field generation for read-only fields

packages/codegen-ui-react/lib/__tests__/__snapshots__/react-component-render-helper.test.ts.snap, packages/codegen-ui-react/lib/__tests__/react-component-render-helper.test.ts, packages/codegen-ui-react/lib/react-component-render-helper.ts, packages/codegen-ui/lib/__tests__/renderer-helper.test.ts, packages/test-generator/integration-test-templates/cypress/e2e/generated-components-spec.cy.ts, packages/test-generator/lib/components/operators/componentWithConcatenation.json
Customers are not able to concat auth bindings
Handle auth props in concat
=> fix: handle auth prop in concat

package-lock.json, packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/__utils__/amplify-renderer-generator.ts, packages/codegen-ui-react/lib/__tests__/__utils__/index.ts, packages/codegen-ui-react/lib/__tests__/__utils__/mock-data-schemas.ts, packages/codegen-ui-react/lib/__tests__/collections/nested-query-collection.test.ts, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/react-studio-template-renderer-helper.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui/example-schemas/authorCollectionComponent.json, packages/codegen-ui/lib/__tests__/generic-from-datastore.test.ts, packages/codegen-ui/lib/generic-from-datastore.ts, packages/codegen-ui/lib/types/data.ts
- allow studio component renderer to accept a generic data schema
- on collections render if the data schema is passed and the selected model has a `hasMany` relationship include the nested query
=> feat: add nested query if data schema is passed down

packages/codegen-ui-react/lib/react-required-dependency-provider.ts
Recommended version for ui-react was set to non-existent version.
Setting to existing: https://www.npmjs.com/package/@aws-amplify/ui-react/v/3.1.0
=> fix: change recommended ui-react version to ^3.1.0

package.json, packages/codegen-ui-react/package.json, packages/codegen-ui/package.json
Unit tests sometimes hang after finishing successfully in CI. This limits workers to factor in the limited capacity in CI.
=> fix: limit workers during testing in ci

CHANGELOG.md, lerna.json, package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/lib/__tests__/__snapshots__/react-theme-studio-template-renderer.test.ts.snap, packages/codegen-ui-react/lib/__tests__/react-theme-studio-template-renderer.test.ts, packages/codegen-ui-react/lib/react-required-dependency-provider.ts, packages/codegen-ui-react/lib/react-theme-studio-template-renderer.ts, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/example-schemas/themeWithBreakpoints.json, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/integration-test-templates/cypress/e2e/primitives-spec.cy.ts, packages/test-generator/package-lock.json, packages/test-generator/package.json
1. Merge down main, resolving merge conflicts
2. Update functional test for SliderField, which is broken due to update in ui-react
=> Merge main

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/imports/import-mapping.ts, packages/codegen-ui-react/lib/react-component-renderer.ts, packages/codegen-ui/lib/generate-form-definition/form-to-component.ts, packages/codegen-ui/lib/utils/form-component-metadata.ts
- Adds onchange prop to "*Fields" components  in forms
- Adds state mutation statements and validation for each field
=> feat: add onchange handling for form renderer

packages/codegen-ui/lib/generate-form-definition/helpers/form-field.ts, packages/codegen-ui/lib/types/form/form-definition-element.ts
`isRequired` and `isReadOnly` have no effect on `SwitchField`. Remove `isRequired` and replace `isReadOnly` with `isDisabled`
=> fix: change props of SwitchField form element

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/react-forms/__snapshots__/form-renderer-helper.test.ts.snap, packages/codegen-ui-react/lib/__tests__/react-forms/form-renderer-helper.test.ts, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/amplify-ui-renderers/form.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui/lib/__tests__/generate-form-definition/form-to-component.test.ts, packages/codegen-ui/lib/types/form/form-metadata.ts, packages/codegen-ui/lib/types/form/index.ts, packages/test-generator/lib/forms/form-create.json, packages/test-generator/lib/forms/form-update.json, packages/test-generator/lib/generators/BrowserTestGenerator.ts, packages/test-generator/lib/generators/NodeTestGenerator.ts, packages/test-generator/lib/models/schema.ts
- generalizes state mutation functions for Forms
- adds props to forms
- removes unused imports in forms
- update tests
=> chore: tidying forms renderer

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/imports/import-collection.ts, packages/codegen-ui-react/lib/imports/import-mapping.ts, packages/codegen-ui-react/lib/index.ts, packages/codegen-ui-react/lib/react-index-studio-template-renderer.ts, packages/codegen-ui/lib/types/form/form-validation.ts, packages/codegen-ui/lib/types/index.ts, packages/codegen-ui/lib/types/view/view.ts, packages/codegen-ui/lib/validation-helper.ts, packages/test-generator/lib/generators/NodeTestGenerator.ts
Updates
- this will update the import for 'validateField' to come from
codegen-ui-react
- update view type to StudioView
- update validation to be rendered during component rendering
=> chore: update render component only

packages/codegen-ui/lib/generate-form-definition/helpers/model-fields-configs.ts, packages/codegen-ui/lib/generate-form-definition/index.ts
separate out and export logic to map model field to field config so that it can be used in Amplify Studio.
Needed in order to take advantage of the case conversion for label and enum mappings for previews.
=> chore: separate out and export logic to map model field to field config

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/form-field.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/form-field.ts, packages/codegen-ui/lib/types/form/form-definition-element.ts, packages/codegen-ui/lib/utils/form-component-metadata.ts
Notes:
- the `immutable` field of the mapped validations in the form definition is for use in Amplify Studio for styling/ UI purposes. It is removed when the customer form is being rendered.
=> feat: add default, unremovable validations for certain form inputs

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/package-lock.json, packages/codegen-ui/lib/generate-form-definition/form-to-component.ts, packages/codegen-ui/package-lock.json, packages/test-generator/package-lock.json
update form-to-component ctaConfig to use children as opposed to labels
to render the button text
=> fix: update label to children for cta buttons on forms

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui/example-schemas/componentWithBreakpoint.json, packages/codegen-ui/lib/renderer-helper.ts, packages/codegen-ui/package-lock.json, packages/test-generator/integration-test-templates/cypress/e2e/complex-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/generate-spec.cy.ts, packages/test-generator/lib/components/variants/componentWithBreakpoint.json, packages/test-generator/lib/components/variants/index.ts
Components should only have default breakpoint mapping and transition styles when there is a 'breakpoint' variant
=> chore: only generate breakpoint mapping on breakpoint variants

.github/workflows/release.yml
sed command in version number can print characters other than version number
- update `sed` command to only print "0-9" and "." to get version number
=> fix: fix release yml

packages/codegen-ui/lib/generate-form-definition/index.ts, packages/codegen-ui/lib/utils/form-to-component/index.ts, packages/codegen-ui/lib/utils/form-to-component/map-form-definition-to-component.ts, packages/codegen-ui/lib/utils/index.ts
We had a backlog task to move form-to-component out of the form definition mapper because it does not quite belong. 
This PR moves it to the util folder, in its own subfolder, to accommodate the growing number of helpers for this logic.
The test file is removed because it didn't contain any tests.
=> chore: move form-to-component util

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts
- Add override types for Form elements
- 
```
export declare type FormCustomCreateOverridesProps = {
FormCustomCreateGrid: GridProps;
RowGrid0: GridProps;
firstName: TextFieldProps;
RowGrid1: GridProps;
loggedInColor: TextFieldProps;
} & EscapeHatchProps;
export declare type FormCustomCreateProps = React.PropsWithChildren<{
overrides?: FormCustomCreateOverridesProps | undefined | null;
} & {
onSubmit: (fields: Record<string, string>) => void;
onCancel?: () => void;
}>;
```
=> feat: add override types to form elements

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/amplify-ui-renderers/amplify-form-renderer.ts, packages/codegen-ui/example-schemas/forms/post-custom-create.json, packages/codegen-ui/lib/__tests__/__utils__/basic-form-definition.ts, packages/codegen-ui/lib/__tests__/utils/form-to-component/map-form-definition-to-component.test.ts, packages/codegen-ui/lib/utils/form-to-component/helpers/map-element-children.ts, packages/codegen-ui/lib/utils/form-to-component/map-form-definition-to-component.ts
Transform `valueMappings` into `option` children for `SelectField` and `Radio` children for `RadioGroupField`. 
Not in scope - handling `bindingProperties` of `valueMappings`, which have to do with relationships
=> feat: render options for SelectField and RadioGroupField

packages/codegen-ui/lib/types/view/view.ts
We do not need appId and environmentName on StudioView to codegen views. The UI extends on this shape for the model, but there, it can set those values as required.
This is motivated by not wanting to pass these values in for auto-gened views in the CLI.
=> chore: make appId and environmentName optional for StudioView

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/react-forms/__snapshots__/form-renderer-helper.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/utils/forms/validation.ts
- Add default validation state 
```useStateMutationAction({` hasError: false, errorMessage: "" });```
- Add onValidate declaration type
- Fix  onSubmitComplete saveSuccessful type to boolean
- Change `validationMessage` in `validateField` to optional
=> chore: fix form types

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/event-targets.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui/example-schemas/datastore/input-gallery.json, packages/codegen-ui/example-schemas/forms/input-gallery-create.json, packages/codegen-ui/lib/__tests__/generate-form-definition/generate-form-definition.test.ts, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/model-fields-configs.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/form-field.ts, packages/codegen-ui/lib/generate-form-definition/helpers/model-fields-configs.ts, packages/codegen-ui/lib/types/form/fields.ts, packages/codegen-ui/lib/types/form/form-definition-element.ts, packages/codegen-ui/lib/types/form/form-metadata.ts, packages/codegen-ui/lib/types/form/index.ts, packages/codegen-ui/lib/utils/form-component-metadata.ts, packages/test-generator/lib/generators/TestGenerator.ts
- `onChange` events need to handle casting to the correct types
- add a casting check before validating value from event changes
=> fix: add type casting when doing on change

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-views.test.ts.snap, packages/codegen-ui-react/lib/__tests__/__utils__/amplify-renderer-generator.ts, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-views.test.ts, packages/codegen-ui-react/lib/amplify-ui-renderers/amplify-view-renderer.ts, packages/codegen-ui-react/lib/imports/import-mapping.ts, packages/codegen-ui-react/lib/index.ts, packages/codegen-ui-react/lib/react-studio-template-renderer-helper.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui-react/lib/react-table-renderer-helper.ts, packages/codegen-ui-react/lib/react-table-renderer.ts, packages/codegen-ui-react/lib/react-utils-studio-template-renderer.ts, packages/codegen-ui-react/lib/views/react-view-renderer.ts, packages/codegen-ui/example-schemas/datastore/post-ds.json, packages/codegen-ui/example-schemas/views/post-table-custom-format.json, packages/codegen-ui/example-schemas/views/post-table-datastore.json, packages/codegen-ui/lib/types/view/view-metadata.ts, packages/test-generator/lib/generators/BrowserTestGenerator.ts, packages/test-generator/lib/generators/NodeTestGenerator.ts
=> fix: expose amplfyViewRenderer and update settings for passing

packages/codegen-ui-react/lib/react-studio-template-renderer-helper.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui-react/package.json
We need to conditionally allow prettier to be called so we don't incur additional performance cost at runtime.
=> feat: allow conditional formatting of outputs

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts
- extend existing validation instead of replacing it if custom validation function
- factor out the validation tasks so that it can be reused on submit later (currently only used on change)
- fix logic for getting if form is valid.
- remove empty error messages on mount
=> chore: change form validation

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/react-forms/__snapshots__/form-renderer-helper.test.ts.snap, packages/codegen-ui-react/lib/amplify-ui-renderers/form.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/forms/typescript-type-map.ts, packages/test-generator/integration-test-templates/cypress/e2e/form-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/generate-spec.cy.ts, packages/test-generator/integration-test-templates/src/App.tsx, packages/test-generator/integration-test-templates/src/FormTests.tsx, packages/test-generator/lib/forms/custom-form-create-dog.json
- validate on submit
- change type of `onValidate` to allow non-async callback
- fix logic for how `onValidate` extends existing validations
- init form integ test
=> chore: change form validation, validate on submit, and init form integ test

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/helpers/index.ts, packages/codegen-ui-react/lib/utils/generate-react-hooks.ts
- adds optional `currentModel` prop to update Form component
- makes `id` prop optional
=> chore: add model prop to update form

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/imports/import-collection.ts, packages/codegen-ui-react/lib/imports/import-mapping.ts
By removing this import generated forms can now use the utils file for
validateField use. This shouldn't be an issue for UI as that does not
render the import source for the files and we can decide the import
value in the UI code.
=> fix: remove @aws-amplify/codegen-ui-react as import source

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/forms/validation.test.ts, packages/codegen-ui-react/lib/utils/forms/validation.ts, packages/codegen-ui/lib/__tests__/generate-form-definition/generate-form-definition.test.ts, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/form-field.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/form-field.ts, packages/codegen-ui/lib/types/form/form-validation.ts, packages/test-generator/integration-test-templates/cypress/e2e/form-spec.cy.ts, packages/test-generator/integration-test-templates/src/FormTests.tsx, packages/test-generator/lib/forms/custom-form-create-dog.json
- Add validation for `PhoneNumberField` (bare bones according to AWSPhone scalar spec)
- Add validation for required fields.
- Do not run validations other than `Required` if input is empty
- Fix validation regex that were not generating correctly in cx project
=> chore: add phone validation, change required validation, and fix regex

packages/codegen-ui/lib/__tests__/__utils__/mock-schemas.ts, packages/codegen-ui/lib/__tests__/generic-from-datastore.test.ts, packages/codegen-ui/lib/generic-from-datastore.ts
The `getGenericFromDataStore` was throwing when there is an associated field spelled out, but it does not actually exist in the schema.
This PR handles when the field is missing. For good measure, it also handles if an associated model were to be missing, although that has not been raised as an issue.
=> fix: do not assume related model or field is in datastore schema

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/__utils__/amplify-renderer-generator.ts, packages/codegen-ui-react/lib/__tests__/forms/__snapshots__/form-state.test.ts.snap, packages/codegen-ui-react/lib/__tests__/forms/__snapshots__/type-helper.test.ts.snap, packages/codegen-ui-react/lib/__tests__/forms/form-state.test.ts, packages/codegen-ui-react/lib/__tests__/forms/type-helper.test.ts, packages/codegen-ui-react/lib/__tests__/react-forms/__snapshots__/form-renderer-helper.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/__tests__/utils/fetch-by-path.test.ts, packages/codegen-ui-react/lib/amplify-ui-renderers/form.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui-react/lib/forms/form-state.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/forms/type-helper.ts, packages/codegen-ui-react/lib/imports/import-mapping.ts, packages/codegen-ui-react/lib/index.ts, packages/codegen-ui-react/lib/react-component-renderer.ts, packages/codegen-ui-react/lib/react-utils-studio-template-renderer.ts, packages/codegen-ui-react/lib/utils/json-path-fetch.ts, packages/codegen-ui/example-schemas/forms/bio-nested-create.json, packages/codegen-ui/lib/types/form/form-metadata.ts, packages/codegen-ui/lib/utils/form-component-metadata.ts, packages/test-generator/lib/generators/TestGenerator.ts
- onChange behavior changes
- refactor useMutation to useState
- each field now has it’s own useState
- for nested Objects it will use the react docs recommendation for setting nested state docs: [https://beta.reactjs.org/learn/updating-objects-in-state#updating-a-nested-object](https://beta.reactjs.org/learn/updating-objects-in-state#updating-a-nested-object)
- nested json has nested validation object types
- there is a fetch util now that will fetch the validation function from the nested object if it exists
- for everything else needed to support nested json it will refer to using flat paths
- validation variable
- error state
- overrides (tbd to see we can get back to this at a later date)
By submitting this pull request, I confirm …
=> feat: add support for nested json

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/utils/forms/array-field-component.ts, packages/codegen-ui/lib/types/form/form-metadata.ts, packages/codegen-ui/lib/types/form/index.ts, packages/codegen-ui/lib/utils/form-component-metadata.ts
- Adds default values for Update form
- update each field state on datastore query
- fix: remove label for ArrayField component
=> fix: add default values for update form

packages/codegen-ui-react/lib/__tests__/forms/validation.test.ts, packages/codegen-ui-react/lib/utils/forms/validation.ts
`validateField` reports no error for fields with multiple validations configured if it passes the first check, even if it would fail any of the remaining conditions.
Refactor `validateField` to only return the result of a rule check if a validation error was found, allowing other configured rules to be checked.
n/a
=> fix: test all configured validations for field

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts
updates the useEffect hook to only update state if record is defined from datastore query
```js
React.useEffect(() => {
const queryData = async () => {
const record = id ? await DataStore.query(Post, id) : post;
if (record) {
setPostRecord(record);
setTextAreaFieldbbd63464(record.TextAreaFieldbbd63464);
setCaption(record.caption);
setUsername(record.username);
setProfile_url(record.profile_url);
setPost_url(record.post_url);
}
};
queryData();
}, [id, post]);
```
=> fix: update form useEffect to conditionally change state if record is defined

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/forms/__snapshots__/type-helper.test.ts.snap, packages/codegen-ui-react/lib/__tests__/forms/type-helper.test.ts, packages/codegen-ui-react/lib/__tests__/react-forms/__snapshots__/form-renderer-helper.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/forms/type-helper.ts
adds the input values and their types to be used by the form hooks
(below is a snippet only pertaining to type changes)
```ts
export declare type ValidationResponse = {
hasError: boolean;
errorMessage?: string;
};
export declare type ValidationFunction<T> = (value: T, validationResponse: ValidationResponse) => ValidationResponse | Promise<ValidationResponse>;
export declare type UseBaseOrValidationType<Flag, T> = Flag extends true ? T : ValidationFunction<T>;
export declare type InputGalleryCreateFormInputValues<useBase extends boolean = true> = {
num?: UseBaseOrValidationType<useBase, number>;
rootbeer?: UseBaseOrValidationType<useBase, number>;
attend?: UseBaseOrValidationType<useBase, boolean>;
maybeSlide?: …
```
=> fix: add inputType for form hook functions

packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui/lib/renderer-helper.ts, packages/codegen-ui/lib/utils/breakpoint-utils.ts, packages/codegen-ui/lib/utils/index.ts
- adds the minimum amount of breakpoint configs required for the hook to work
- sorts the breakpoints according to size as the base will use the smallest size if not specified
=> fix: include minimum breakpoints required

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui-react/lib/forms/index.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/forms/type-helper.ts, packages/codegen-ui/example-schemas/forms/bio-nested-update.json, packages/codegen-ui/example-schemas/forms/input-gallery-update.json, packages/codegen-ui/example-schemas/forms/post-custom-update.json, packages/codegen-ui/lib/utils/index.ts
- add initialData prop to pass for on update custom forms
- set the state in a useEffect similar to on update for datastore backed forms
- fix override onchange to pass the value with the model field object into the onChange hook
- move `buildFormPropNode` to type-helper
- remove defaultValue from controlled components as the value will take its place
=> fix: onChange overrides to use onChange value and add useEffect initial data for update custom forms

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui-react/lib/forms/form-state.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/utils/forms/array-field-component.ts
- create reset values functions to reset state with the reset button
- add helper methods for setting set
- unify name source for setCurrentValue in arrayfield
=> fix: onClear to reset state values and errors

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui-react/lib/forms/form-state.ts
- let validation tasks run without creating an async function in onBlue
- add optional flag for building access chain
- simplify call to reset values when resetting form
=> fix: remove async from onblur

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/utils/forms/array-field-component.ts
If an child arrays is null, we were throwing an array. This fix adds a nullable operator to handle this.
=> fix: handle nullable child arrays

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts
Make `onChange` function synchronous. The motivation is that under certain circumstances, async `onChange` will set the cursor to the end of the text. Behavior like [this](https://github.com/mlaursen/react-md/issues/572)
Confirmed that validations still work.
=> chore: make onChange synchronous

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/react-form-renderer.ts
1. Use `initialData` when resetting form
2. Change initial values whenever `initialData` changes
=> fix: reset custom update form to initial data

packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/model-fields-configs.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/model-fields-configs.ts
do not map non-model fields into input elements by using the helper `checkIsSupportedAsFormField`
Additional change: set readOnly to false for relationship test example so that is not the trait that causes it to be excluded. It should be excluded because it's a relationship, not because readOnly is true.
=> chore: do not autogen non-model fields

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/forms/value-mappers.test.ts, packages/codegen-ui-react/lib/forms/component-helper.ts, packages/codegen-ui-react/lib/forms/event-targets.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/utils/forms/value-mappers.ts, packages/codegen-ui/example-schemas/datastore/blog.json, packages/codegen-ui/example-schemas/forms/input-gallery-update.json, packages/codegen-ui/lib/utils/index.ts
- handle defaultValues date associated fields
- for `AWSTimestamp` this will convert the epoch seconds/milliseconds to datetime-local input
- for `AWSDateTime` will remove the 'Z' character so the date is laid out correctly in the input field
note: seconds/milliseconds are not editable
=> fix: timestamp formatting in defaultValue

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/utils/forms/array-field-component.ts
…y string
https://app.asana.com/0/1202966106210868/1203050023493661/f
I updated the addItem code to allow for the number 0
I updated the default values for string fields to be an empty string. This prevents react components from going from uncontrolled to controlled components.
=> fix: accept 0 for number fields

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui/example-schemas/forms/custom-with-array-field.json, packages/codegen-ui/example-schemas/forms/post-custom-create.json, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/form-field.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/form-field.ts, packages/codegen-ui/lib/types/form/form-definition-element.ts
https://app.asana.com/0/1202185248783861/1203023473438342/f
Mapping AWSPhone to TextField w/ type='tel' until ui-react supports PhoneNumberField component as a fully controlled component.
=> fix: map AWSPhone to TextField

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts
_Problems:_
- `SwitchField` child of `ArrayField` had 2 `value` props.
- child of `ArrayField` always had `value` prop, even if the component did not need to be controlled. It would cause issues like TextField tied to AWSTimestamp DataStore field resetting to undefined `onChange`.
- child of `ArrayField` always had `value` prop even when it needed to be something else to be effective, like `isPressed`, `isChecked`, etc.
_Changes:_
- Change `value` on `SwitchField` to `isChecked`. `value` has no effect on this component.
- Remove `value` on child of `ArrayField` on components that don't need it.
- For components that do need to be controlled, render the correct prop (e.g. `isPressed`), not always just `value`
By submitting this pull request, I confirm that you can …
=> fix: fix value props on ArrayField child

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts
Problem:
1) failing form validation because JSON validator wants to parse the string 
2) when value is optional and undefined, JSON.parse is failing
Confirmed that it saves to DS even when not parsed.
=> fix: do not parse AWSJSON for submit

packages/codegen-ui-react/lib/__tests__/__utils__/amplify-renderer-generator.ts, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json
`Schema` is no longer being exported from `codegen-ui`, so test throws a type error when running. This adds datastore as a dev dep of `codegen-ui-react` directly.
=> fix: add datastore as dev dep

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/component-helper.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui/example-schemas/datastore/blog.json
Removing `value` from the children of `ArrayField` broke Badge editing state. For the `TextField`, etc. to populate with the existing value when a Badge is clicked for edit, the field must be controlled i.e. must have `value`.
This PR
- adds back the `value` for children of `ArrayField`
- pulls in conversions for dates and times in rendering the value. Note the conversions are not completely polished atm but is better than behavior when no conversion at all. TODO noted for solidifying the conversions and making all components controlled, even when not nested within `ArrayField`
=> fix: make ArrayField children value controlled again

packages/codegen-ui/lib/__tests__/check-support.test.ts, packages/codegen-ui/lib/__tests__/generate-form-definition/generate-form-definition.test.ts, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/form-field.test.ts, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/model-fields-configs.test.ts, packages/codegen-ui/lib/__tests__/utils/form-component-metadata.test.ts, packages/codegen-ui/lib/check-support.ts, packages/codegen-ui/lib/generate-form-definition/helpers/field-type-map.ts, packages/codegen-ui/lib/generate-form-definition/helpers/form-field.ts, packages/codegen-ui/lib/generate-form-definition/helpers/model-fields-configs.ts, packages/codegen-ui/lib/types/form/fields.ts, packages/codegen-ui/lib/types/form/form-definition-element.ts, packages/codegen-ui/lib/types/form/form-definition.ts, packages/codegen-ui/lib/types/form/form-metadata.ts, packages/codegen-ui/lib/types/form/index.ts, packages/codegen-ui/lib/utils/form-component-metadata.ts
- Allow forms with required relationships to be mapped
- Map relationship fields to form definition element and form metaData as `Autocomplete`
- Generate default valueMappings from related model info for `HAS_ONE` model-type relationships
=> feat: init form support for has-one relationship

packages/codegen-ui-golden-files/lib/react/forms/datastore-create-form-with-has-one-relationship/BookCreateForm.jsx, packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/all-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/display-value.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/event-handler-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/form-state.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/index.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/map-from-fieldConfigs.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/model-fields.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/render-checkers.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/validation.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/value-props.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui/example-schemas/datastore/book.json, packages/codegen-ui/example-schemas/forms/book-datastore-create.json, packages/codegen-ui/lib/__tests__/utils/form-component-metadata.test.ts, packages/codegen-ui/lib/types/form/form-metadata.ts, packages/codegen-ui/lib/utils/form-component-metadata.ts
- Map props onto the `Autocomplete` component generated by a `HAS_ONE` relationship model-type field
- Build the displayValue object and import required models (removed by prettier until actually used)
- Fix a bug in onChange override where the value was not being set correctly
- Change the snapshot test's field name from `primaryAuthor` to `primary-author` to test out sanitization
- Consolidate fieldConfigs iterations to cut down on run time
- camelCase while sanitizing field names
=> chore: map props on relationship-based Autocomplete

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/react-forms/__snapshots__/form-renderer-helper.test.ts.snap, packages/codegen-ui-react/lib/__tests__/react-forms/form-renderer-helper.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/event-handler-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/type-helper.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/map-cta.test.ts, packages/codegen-ui/lib/__tests__/utils/form-utils.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/map-cta.ts, packages/codegen-ui/lib/utils/form-utils.ts
asana task: https://app.asana.com/0/1202185248783861/1203024227380062/f
- hide cancel component generation by editing cta matrix
- hide onCancel variable and type via shouldIncludeCancel helper function
=> fix: by default hide cancel

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/form-state.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/index.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/invalid-variable-helpers.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/render-array-field.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/react-component-renderer.ts, packages/codegen-ui-react/lib/utils/forms/array-field-component.ts
- Add props to the instantiation of ArrayField wrapping the Autogen component
- Handle new props in the ArrayField component
=> chore: modify ArrayField to support has-one relationships

packages/codegen-ui-golden-files/lib/react/forms/datastore-create-form-with-has-one-relationship/BookCreateForm.jsx, packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/amplify-ui-renderers/form.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/all-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/cta-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/display-value.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/event-handler-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/form-state.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/invalid-variable-helpers.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/validation.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui/example-schemas/forms/book-datastore-create.json, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/model-fields-configs.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/model-fields-configs.ts
- support fields that are not of model type but has relationship
Bug fixes like:
- DataStore query rendering twice when model used twice
- runValidationTasks need to use display value
- Autocomplete suggestions assume wrong shape of model records
- Helper for property access was wrong
=> chore: support not-model HAS_ONE relationships

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/display-value.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/type-helper.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts
Map types for model fields in d.ts
Address feedback on prev PR - Use variable instead of static string for accessing record.
=> chore: map type file for model fields

.github/workflows/check.yml, packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts
Update forms fail to update data after the first update due to stale data.  By performing a fresh query before submit, we ensure we are performing mutations on the latest state.  
See https://docs.amplify.aws/lib/datastore/data-access/q/platform/js/#create-and-update
=> fix: refresh stale data on update form

.github/workflows/check.yml, README.md, scripts/integ-test.sh
*Issue #, if available:* N/A
*Description of changes:* Adds `TZ=UTC` env variable setup before running cypress integration tests.
=> chore: set timezone to UTC before starting cypress tests

.github/workflows/check.yml, packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, scripts/integ-test.sh
- if url field value is empty string fallback to undefined for datastore
=> fix: allow empty string for url field

packages/codegen-ui-react/lib/__tests__/forms/validation.test.ts, packages/codegen-ui-react/lib/utils/forms/validation.ts
- Change `< `char validation to `<=`
=> fix: less than char validation

.github/workflows/check.yml, packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/imports/import-collection.test.ts, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/helpers/index.ts, packages/codegen-ui-react/lib/imports/import-collection.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui-react/lib/workflow/action.ts, packages/codegen-ui/example-schemas/bindings/data/dataBindingNamedFlex.json, packages/codegen-ui/example-schemas/collectionWithModelNameCollisions.json, scripts/integ-test.sh
- Alias imported model names colliding with primitives/models/child components
=> fix: alias model names collision with component types

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/component-helper.ts, packages/codegen-ui-react/lib/forms/form-state.ts, packages/codegen-ui-react/lib/workflow/mutation.ts, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/form-field.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/form-field.ts, packages/codegen-ui/lib/types/form/form-definition-element.ts
Make CheckboxField a controlled component similar to ToggleButton so that the field properly renders a default state of "checked" when it's supposed to.
Update form setting checkbox to checked, and then reload form
https://user-images.githubusercontent.com/1263887/198681650-ed1fb596-4883-414c-a248-c793194a60fd.mov
Current experience, loading form with checkbox in "checked" state does not set it to checked properly
https://user-images.githubusercontent.com/1263887/198681863-de079ca6-ae7b-42fb-8124-3406ba92d164.mov
=> fix: forms checkbox to reflect correct model state

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/amplify-ui-renderers/form.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts
- rebase with main
- fix model name query for change in main
=> merge from main

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/forms/validation.test.ts, packages/codegen-ui-react/lib/__tests__/imports/import-collection.test.ts, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/amplify-ui-renderers/form.ts, packages/codegen-ui-react/lib/forms/component-helper.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui-react/lib/forms/form-state.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/forms/type-helper.ts, packages/codegen-ui-react/lib/helpers/index.ts, packages/codegen-ui-react/lib/imports/import-collection.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui-react/lib/utils/forms/validation.ts, packages/codegen-ui-react/lib/workflow/action.ts, packages/codegen-ui-react/lib/workflow/mutation.ts, packages/codegen-ui/example-schemas/bindings/data/dataBindingNamedFlex.json, packages/codegen-ui/example-schemas/collectionWithModelNameCollisions.json, packages/codegen-ui/example-schemas/datastore/flex.json, packages/codegen-ui/example-schemas/forms/flex-datastore-create.json, packages/codegen-ui/example-schemas/forms/flex-datastore-update.json, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/form-field.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/form-field.ts, packages/codegen-ui/lib/types/form/form-definition-element.ts, packages/codegen-ui/lib/utils/index.ts
Forms hotfixes:
1. https://github.com/aws-amplify/amplify-codegen-ui/pull/740
2. https://github.com/aws-amplify/amplify-codegen-ui/pull/738
3. https://github.com/aws-amplify/amplify-codegen-ui/pull/739
4. https://github.com/aws-amplify/amplify-codegen-ui/pull/735
5. https://github.com/aws-amplify/amplify-codegen-ui/pull/733
=> Forms hotfixes

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/react-form-renderer.ts
We currently don't allow style props to be passed to the form if the customer is using TypeScript
This adds the `React.CSSProperties` type to the props which allows the customer to either specify a `className` or individual styles.
=> feat: allow style related props

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-state.ts
https://app.asana.com/0/1202293561809020/1203339958100504/f
For AWSJSON type fields, when a field value was being from an existing record (from a datastore record for example) the field value could be a JavaScript object. So the field value would show the toString output of the object which was the old [object Object] string which looks bad and broken.
With this update, the form will stringify the object so the field will display the string version of the JSON as expected.
=> fix: stringify existing AWSJSON field value

packages/codegen-ui-react/lib/react-required-dependency-provider.ts
[#11397 on amplify-cli](https://github.com/aws-amplify/amplify-cli/issues/11397)
I changed some capitalization and added the word Amplify in front of Studio to fix some grammar issues.
=> fix: fix grammar in pull warning message

packages/codegen-ui-react/lib/react-required-dependency-provider.ts
*Motivation:*
- We need v5 of aws-amplify to support relationships
- ui-react 4.0.1 has fixes we need to support aws-amplify v5.
aws-amplify versions - https://www.npmjs.com/package/aws-amplify?activeTab=versions
ui-react versions - https://www.npmjs.com/package/@aws-amplify/ui-react?activeTab=versions
=> chore: rev recommended ui-react to ^4.0.1 and add aws-amplify ^5.0.2

packages/test-generator/integration-test-templates/cypress/e2e/generated-components-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/views-spec.cy.ts
The Amplify UI team released a patch that allows our integ tests to pass again
=> chore: add back integration tests

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts
- pass in the current value instead of the prev one into the `onChange` override
- style change: remove brackets from key (it used to render when `value` specified as value.
=> fix: fix value passed to onChange override

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/utils/forms/array-field-component.ts
- fix variable name for `items` and `inputFieldRef` on `ArrayField` when the associated field is a nested array with a name that does not work as a js variable.
=> fix: fix variables for nested arrays

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/amplify-ui-renderers/form.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui-react/lib/react-component-render-helper.ts, packages/codegen-ui/example-schemas/forms/post-custom-create-custom-gaps.json
The CTA row for forms do not use the configured gap sizes between the buttons on the right side. This is inconsistent with what customers see when actively editing their forms within Studio causing the view to shift as they toggle between edit and preview modes.
PR adds a gap property to the flex element surrounding the right-side CTA buttons, supporting both fixed values and design tokens.
=> fix: generate gap attribute for CTA row

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/all-props.ts, packages/codegen-ui-react/lib/utils/forms/array-field-component.ts
The label field for ArrayField was rendering in two places if the child field was anything other than `Autocomplete`. This fixes it so it's in one place only.
=> fix: fix ArrayField label

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/cta-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/form-state.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/index.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui/example-schemas/forms/member-datastore-update-belongs-to.json
This change adds support for belongsTo relationships in update forms by grabbing the nested model from the target record to update.
=> Add support for update forms with belongsTo relationship

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/component-helper.ts, packages/codegen-ui/example-schemas/forms/bio-nested-create.json
Give boolean fields the fully qualified name for the default value. 
For example, in the case of nested fields, it was setting isChecked to the nested object so it was passing an object `{}` to isChecked which was causing errors with the UI Component. UI Component expects a boolean or an undefined value.
=> fix: nested boolean field isn't controlled

packages/test-generator/integration-test-templates/cypress/e2e/create-form-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/generate-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/update-form-spec.cy.ts, packages/test-generator/integration-test-templates/src/App.tsx, packages/test-generator/integration-test-templates/src/CreateFormTests.tsx, packages/test-generator/integration-test-templates/src/UpdateFormTests.tsx, packages/test-generator/lib/forms/datastore-form-update-all-supported-form-fields.json
Things will get messy with DataStore records, etc. if we keep create and update forms in the same page. This breaks out `FormTest` into separate components - `CreateFormTest` and `UpdateFormTest` and sets up tests accordingly. It also inits the update form for the `AllSupportedFormFields` model.
=> chore: break out form tests by create and update

packages/test-generator/integration-test-templates/src/ComponentTests.tsx, packages/test-generator/integration-test-templates/src/ViewTests.tsx
Changes in ui-react types is breaking build. This typecasts until the Amplify UI team figures out a way forward.
=> chore: temporarily typecast custom theme

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/react-component-render-helper.ts, packages/codegen-ui-react/lib/react-component-renderer.ts, packages/codegen-ui/example-schemas/customChildMalformedProperty.json, packages/codegen-ui/example-schemas/forms/input-gallery-create.json, packages/codegen-ui/lib/generate-form-definition/generate-form-definition.ts, packages/codegen-ui/lib/generate-form-definition/helpers/form-field.ts, packages/codegen-ui/lib/generate-form-definition/helpers/map-cta.ts, packages/codegen-ui/lib/generate-form-definition/helpers/position.ts, packages/codegen-ui/lib/renderer-helper.ts, packages/codegen-ui/lib/utils/component-metadata.ts, packages/codegen-ui/lib/utils/form-to-component/helpers/map-element-children.ts, packages/codegen-ui/lib/utils/state-reference-metadata.ts
customers are encountering runtime exceptions with error logs indicating that the `in` operator is being used for type narrowing but the right hand side is not compatible with the operator (unexpected string value). Adding a `typeof` check to ensure the value is non-primitive prior to narrowing using `in` will grant us additional runtime safety and allow codegen to continue executing without error.
[TS Playground example](https://www.typescriptlang.org/play?ts=4.4.4#code/PTAEEsDsDcEMBtwBMKQA4FcAuBnUkBTAlLAe1ACMDQBjWHLY0e0AA1kgE9XKC6Mc1LAAsCAJ2rg8NUgFs04eAQC0WcLOo5YAMwJZOobaTGgR1VlB6k042GTEA6ALAAoEKlDGk40+QDmeqBiGJBqGqBauvoANKaiQeB+wljKwhxIyjjI1ITEeGSgrjKQDKYEDACS6NgAXBwGALygAN6uoO2gcPAY5TVszV09fQBEjAzDAL6sbR2uE64LLq7uYonJqemZ2aCyAli8+KSQym …
=> fix: improve runtime safety for usage of the in operator

packages/test-generator/integration-test-templates/cypress/e2e/create-form-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/update-form-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/utils/form.ts, packages/test-generator/integration-test-templates/src/UpdateFormTests.tsx, packages/test-generator/lib/forms/datastore-form-update-all-supported-form-fields.json
- pass in record to datastore update form
- add test for hasOne relationship update
- break out cypress helpers into utils file
- make action more specific in create form test
=> chore: add integ test for update hasOne relationship

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/amplify-ui-renderers/__snapshots__/primitives.test.ts.snap, packages/codegen-ui-react/lib/react-component-renderer.ts, packages/test-generator/integration-test-templates/cypress/e2e/generated-components-spec.cy.ts, packages/test-generator/integration-test-templates/src/ComponentTests.tsx
*Problem*
if I pass `width` like so <MyComponent width="100px" />
It will not get applied to a variant if it supplies an override of `width`
- have `rest` props override variant values (as well as values from `override` prop)
- add integ test coverage
=> fix: have rest props override variant values

packages/codegen-ui/lib/__tests__/generate-form-definition/generate-form-definition.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/position.ts
- remove existing element in matrix when requeued
- fixes bug while reordering elements in UI
=> fix: remove existing element in matrix when requeued

packages/codegen-ui-react/lib/__tests__/__utils__/amplify-renderer-generator.ts, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts
https://app.asana.com/0/1202293561809020/1203468156027560/f
When rendering component only, the client needs to know what the import alias names are for the required data models. This change adds the import aliases to the requiredDataModels value returned by the renderComponentOnly method, so the client knows which alias to use for the data model.
=> fix: add importCollection to renderComponentOnly return

packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts
- add datamodel to requiredDataModels for renderComponentOnly
=> fix: add form datamodel to requiredDataModels for renderComponentOnly

packages/test-generator/integration-test-templates/src/ComponentTests.tsx, packages/test-generator/integration-test-templates/src/ViewTests.tsx
This reverts commit 018975d3f0381c662529e11296ef6c6140509e3a.
Amplify UI pushed the fix for the breaking types so we can revert this.
=> Revert "chore: temporarily typecast custom theme"

packages/codegen-ui-react/lib/__tests__/__utils__/amplify-renderer-generator.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts
- cherry-pick requiredDataModels fixes
- https://github.com/aws-amplify/amplify-codegen-ui/pull/815
- https://github.com/aws-amplify/amplify-codegen-ui/pull/813
=> Cherry pick requiredDataModels fixes

scripts/integ-setup.bat, scripts/integ-setup.sh
Cypress did a major version bump and it's breaking our integ tests. Looking to rev our tests to accommodate, but in the meanwhile, unblocking merges w/ this.
=> chore: pin cypress to 11

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/cta-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts, packages/codegen-ui/lib/__tests__/generic-from-datastore.test.ts, packages/codegen-ui/lib/__tests__/utils/form-component-metadata.test.ts, packages/codegen-ui/lib/generic-from-datastore.ts, packages/codegen-ui/lib/types/data.ts, packages/test-generator/integration-test-templates/cypress/e2e/update-form-spec.cy.ts
We currently can't remove `hasOne` or `belongsTo` relationships.
It's a DataStore issue being tracked here https://github.com/aws-amplify/amplify-js/issues/10750
But in the meanwhile, this is the temporary solution.
Integration tests included.
=> fix: add temp solution for removing hasOne & belongsTo relationships

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/amplify-ui-renderers/customComponent.ts, packages/codegen-ui/example-schemas/custom/aliasParent.json
- Handles aliased children which would otherwise share the same name as primitives.
- Change import file path to point to source component of aliased child.
=> fix: update import file path to handle aliased children

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui/lib/__tests__/generate-form-definition/generate-form-definition.test.ts, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/model-fields-configs.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/model-fields-configs.ts
Update model field config to set field's readOnly value to true if the field is a primary key.
=> chore: set primary key fields to read only

packages/codegen-ui/lib/__tests__/generate-form-definition/generate-form-definition.test.ts, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/form-field.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/form-field.ts, packages/codegen-ui/lib/types/form/input-config.ts
When a field is renamed in DataStore, we lose the type if the field is customized which causing rendering errors. Instead, we should default back to a text field.
=> fix: handle customized fields getting renamed

packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/imports/import-collection.ts
CMSv2 team is asking for an interface that would allow them to use just `importCollection` and get rid of dependency on `requiredDataModels`. This adds a method to `importCollection` that would let them do this easily.
=> feat: add getAliasMap method to importCollection

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui/example-schemas/datastore/cpk-relationships.json, packages/codegen-ui/lib/__tests__/__utils__/mock-schemas.ts, packages/codegen-ui/lib/__tests__/generic-from-datastore.test.ts, packages/codegen-ui/lib/__tests__/utils/form-component-metadata.test.ts, packages/test-generator/integration-test-templates/cypress/e2e/update-form-spec.cy.ts, packages/test-generator/integration-test-templates/src/UpdateFormTests.tsx, packages/test-generator/integration-test-templates/src/models/index.d.ts, packages/test-generator/integration-test-templates/src/models/schema.js, packages/test-generator/lib/models/schema.ts
The schemas testing CPK were generated without `features.respectprimarykeyattributesonconnectionfield` set to `true` in the `cli.json`. This updates the schemas to those generated with the flag set to `true`, so that they are a more accurate representation of customer input.
=> test: change schemas for cpk tests

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui/example-schemas/forms/flex-datastore-update.json
- aliased model name breaking datastore query in update form 
- use lowercased dataTypeName value for datastore query
=> fix: use lowercase datatype name for update form query

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/amplify-ui-renderers/form.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/cta-props.ts, packages/test-generator/integration-test-templates/cypress/e2e/create-form-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/update-form-spec.cy.ts
If a non-required field is empty, DataStore.save would fail because we would try to save `""` for `AWSEmail`, etc.
=> fix: allow empty non-required fields to save

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/event-handler-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/event-targets.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/form-state.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/value-props.ts
*Issues addressed:*
- integer fields in update form - type some number (e.g 45); then backspace the entire number; click submit and the first digit will save (e.g. 4) instead of null
- integer, float, and json fields in update form - type some value (e.g 45); then highlight the entire number with your cursor and then remove the entire value with a single backspace. click submit and then the value is still saved (e.g. 45) instead of null
- float fields in update form - type some number (e.g. 78); then backspace the entire number, and click submit. the record is updated to include ‘0’ in the float field instead of null
- datetime and timestamp fields - if i backspace multiple times to delete an existing value in one of these fields and then click ‘submit,’ the …
=> fix: fix updates in scalar fields

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/cta-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/model-fields.ts, packages/codegen-ui/example-schemas/datastore/post.json, packages/test-generator/integration-test-templates/cypress/e2e/create-form-spec.cy.ts, packages/test-generator/integration-test-templates/src/UpdateFormTests.tsx, packages/test-generator/integration-test-templates/src/models/index.d.ts, packages/test-generator/integration-test-templates/src/models/index.js, packages/test-generator/integration-test-templates/src/models/schema.js, packages/test-generator/lib/models/schema.ts
non-model arrays were blocking successful save because the items need to be parsed.
Integ test included
*Addtional changes:*
remove redundant operation for empty strings. There's integ test coverage to make sure what it had inteded to fix stays fixed.
=> fix: parse values for non-model arrays

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/amplify-ui-renderers/customComponent.ts, packages/codegen-ui-react/lib/helpers/index.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui/example-schemas/custom/aliasParent.json, packages/codegen-ui/lib/__tests__/__snapshots__/validation-helper.test.ts.snap, packages/codegen-ui/lib/__tests__/validation-helper.test.ts
- Alias import to match aliased component type from original component. Example: `import { Grid as GridCustom } from "./Grid"`
- Point props import to original component - `import { GridProps } from "./Grid"` instead of `import { GridCustomProps } from "./GridCustom"`
=> fix: update imports and props for aliased components

package-lock.json, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-react/lib/forms/form-renderer-helper/model-values.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/render-checkers.ts, packages/codegen-ui-react/package-lock.json, packages/codegen-ui/lib/utils/form-component-metadata.ts, packages/codegen-ui/package-lock.json, packages/test-generator/package-lock.json
Using functions imported from devDep `@aws-amplify/datastore` is causing CLI e2e tests to fail. 
This removes their usage and replaces w/ our own helper.
=> fix: remove functions imported from devDep

.github/workflows/canaries.yml
https://app.asana.com/0/1203493556028707/1203510624767048/f
Add the oidc role for the job to assume instead of using long lived credentials.
=> fix: use oidc provider for canary metrics

.github/workflows/canaries.yml, .github/workflows/check.yml
https://app.asana.com/0/1203493556028707/1203510624767048/f
Removes the e2e test account credentials and uses github oidc and aws account integration instead.
=> fix: remove e2e test account credentials

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/amplify-ui-renderers/form.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/bidirectional-relationship.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/cta-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/form-state.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts
Logically, there should be a 1-1 relationship between hasOne and belongsTo.
But DS does not enforce it.
So this is to enforce it during form submission.
=> fix: enforce bidirectionality between hasOne and belongsTo

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/cta-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/form-state.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/parse-fields.ts
- parse nonmodel fields on submit
- stringify nonmodel fields on update form load
=> fix: parse and stringify nonmodel fields

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts, packages/codegen-ui/example-schemas/datastore/school-student.json, packages/test-generator/integration-test-templates/cypress/e2e/update-form-spec.cy.ts
When the linking field of a child data is set up to be required by the user for has many relationship, a confusing error message is shown to the user.
This change catches the error message returns from the update request, and throws an new error with more descriptive message.
=> fix: hasMany update form should throw better error message for invalid schema

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/model-fields-configs.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/model-fields-configs.ts
If related model name is `Salad`, we want the default placeholder to be `Search Salad` for the Autocomplete representing the relationship.
=> chore: add placeholder to relationship fields

packages/codegen-ui/example-schemas/datastore/composite-relationships.json, packages/codegen-ui/example-schemas/datastore/cpk-relationships.json, packages/codegen-ui/lib/__tests__/__utils__/mock-schemas.ts, packages/test-generator/integration-test-templates/src/models/schema.js, packages/test-generator/lib/models/schema.ts
There was a hotfix for an issue effecting hasOne-belongsTo relationships in the CLI (https://github.com/aws-amplify/amplify-cli/pull/11736) 
This PR updates the schemas used in tests to the one generated by the latest CLI.
We have an outstanding task to generate the schemas dynamically in the tests using the introspection API.
When we have that in place, we will not need to do manual updates like this.
=> test: update cpk and composite schemas

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui/example-schemas/forms/composite-toy-datastore-create.json, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/model-fields-configs.test.ts, packages/codegen-ui/lib/__tests__/generic-from-datastore.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/model-fields-configs.ts, packages/codegen-ui/lib/generic-from-datastore.ts, packages/codegen-ui/lib/types/data.ts, packages/test-generator/integration-test-templates/cypress/e2e/generate-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/update-form-spec.cy.ts, packages/test-generator/integration-test-templates/src/UpdateFormTests.tsx, packages/test-generator/lib/forms/datastore-form-update-composite-toy.json, packages/test-generator/lib/forms/index.ts
For 1:m relationship (Post:Comment), there is a secondary index on Comment that allows it to be queried by Post's primary key(s) - https://docs.amplify.aws/cli/graphql/data-modeling/#has-many-relationship.
We want to render the field for this index/indices so that the customer can configure relationships from the child.
=> chore: render indices on children of hasMany

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/model-fields-configs.test.ts
*What happened:*
1. PRs that added more unit tests passed checks
2. PR for adding placeholder was merged
3. PRs that added more unit tests were merged
4. Unit tests are now failing because they do not contain placeholders.
=> test: update tests with placeholders

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts, packages/codegen-ui/example-schemas/datastore/comment-hasMany-belongsTo-relationships.json, packages/codegen-ui/example-schemas/forms/comment-datastore-create.json, packages/codegen-ui/example-schemas/forms/org-datastore-update.json, packages/codegen-ui/lib/__tests__/__utils__/mock-schemas.ts, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/model-fields-configs.test.ts, packages/codegen-ui/lib/__tests__/generic-from-datastore.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/model-fields-configs.ts, packages/codegen-ui/lib/generic-from-datastore.ts, packages/codegen-ui/lib/types/data.ts
If Post `hasMany` Comment and Comment `belongsTo` Post:
- update `belongsTo` on Comment through the Post form
- render index for `hasMany` relationship on Comment form if this index is different from that of the `belongsTo` relationship.
- if `belongsTo` is required on Comment, set `canUnlink..` to false for Post's comments field.
=> feat: support bidirectional hasMany

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/cta-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/parse-fields.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts
When a customer has a `!` next to their array for `hasMany` or `manyToMany` relationships, forms will throw because we are explicitly setting them to `undefined`.
This PR excludes the fields instead, allowing the required array fields to not throw.
Note that the `!` next to the array does not actually have any meaning for the relationship itself, whatever the customer's intent is.
Q: Why do we have to exclude the fields? Why not just leave in `[]`?
A: For models with CPKs, leaving in `[]` will throw.
Consolidate logic in the CTA DS call renderer so that it's more maintainable. 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
=> fix: allow required arrays in relationships

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/all-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/event-handler-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/render-array-field.ts, packages/codegen-ui-react/lib/react-component-renderer.ts, packages/codegen-ui-react/lib/utils/forms/array-field-component.ts, packages/test-generator/integration-test-templates/cypress/e2e/create-form-spec.cy.ts
Have errors on ArrayFields show up even when not in editing mode.
Integ test included.
Additional change - refine validation behavior for Autocompletes - refresh validation onSelect.
=> fix: show arrayField error message in non-edit mode

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/utils/forms/value-mappers.ts, packages/test-generator/integration-test-templates/cypress/e2e/create-form-spec.cy.ts
When the customer inputs 12AM in either the timestamp field or the date time field, the value would not persist and their field would reset to blank. This was because 12AM was being converted to the 24th hour by `Intl.DateTimeFormat` in chrome ([related issue](https://support.google.com/chrome/thread/29828561?hl=en)) and the `datetime-local` `type` `input` element could not handle this. 
The workaround is to replace `hour12: false'` with `hourCycle: 'h23'`.
Added an integ test. Made sure it fails before this change.
=> fix: handle 12AM when converting to local time

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/validation.ts, packages/test-generator/lib/forms/datastore-form-create-cpk-teacher.json
When fields have concatenated display values, we were incorrectly passing validation for `undefined` values on submit.
Integ test modified to cover this case. Made sure it fails before this change.
=> fix: correctly validate on submit for fields with concat display values

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/event-handler-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/event-targets.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/value-props.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui/example-schemas/forms/input-gallery-create.json, packages/codegen-ui/lib/generate-form-definition/helpers/field-type-map.ts, packages/codegen-ui/lib/types/form/form-metadata.ts, packages/test-generator/integration-test-templates/cypress/e2e/create-form-spec.cy.ts
We currently default AWSTimestamp to DateTimeField, which does not have the option to specify seconds. So we're switching to NumberField, with an option to override to DateTimeField.
=> feat: change default component for AWSTimestamp to NumberField

packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/model-fields-configs.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/model-fields-configs.ts
We don't want a drift between customer's experience in Studio and CLI. We will roll in the transition to NumberField with relationship support, riding on that feature flag.
=> chore: conditionally choose default component for AWSTimestamp

packages/codegen-ui-react/lib/__tests__/forms/validation.test.ts, packages/codegen-ui-react/lib/utils/forms/validation-helpers.ts, packages/codegen-ui-react/lib/utils/forms/validation.ts
- fix before/after validation for parsing dates without alpha characters ex: 2022-01-01 and 01/01/2022
=> fix: change timestamp check in date validation function

packages/codegen-ui-react/lib/__tests__/__snapshots__/react-component-render-helper.test.ts.snap, packages/codegen-ui-react/lib/__tests__/react-component-render-helper.test.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui/lib/types/bindings.ts
Adds the operandType property which is what was created to allow boolean operands on the conditional component property. 
Adds this same conditional property feature to the predicate.
=> feat: allow boolean operand on predicate

packages/codegen-ui-react/lib/__tests__/__snapshots__/react-component-render-helper.test.ts.snap, packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/react-component-render-helper.ts, packages/codegen-ui/example-schemas/collectionWithModelNameCollisions.json
Added another test case for Predicate operandType.
The conditional property code was wordy because it's using optional chaining and validating references between nested objects with `&&`. Using both isn't necessary.
If the object is null or undefined, the optional chaining short circuits returns undefined.
It looked like `user?.lastName && user?.lastName == \\"Bound Value\\"` and `buttonColor && buttonColor == \\"red\\" ? true : false}`
This commit updates it to remove the the `&&`
=> fix: update conditional prop codegen

packages/test-generator/integration-test-templates/cypress/e2e/form/DSAllSupportedFormFields-spec.cy.ts, packages/test-generator/integration-test-templates/src/FormTests/DSAllSupportedFormFields.tsx
For the Update AllSupportedFormFields form in the cypress tests, adds value deletion tests for all fields.
=> chore: add deletion tests for AllSupportedFormFields

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/all-props.ts, packages/codegen-ui/example-schemas/forms/custom-with-array-field.json
- Autocomplete component needs labelHidden={false} prop in order for label to show. It is defaulted to true
- https://ui.docs.amplify.aws/react/components/autocomplete?tab=props
=> chore: add false labelHidden prop to autocomplete

packages/codegen-ui/lib/__tests__/__utils__/mock-schemas.ts, packages/codegen-ui/lib/__tests__/generic-from-datastore.test.ts, packages/codegen-ui/lib/generic-from-datastore.ts
https://github.com/aws-amplify/amplify-studio/issues/825
Improve join table identification. We were incorrectly identifying certain models with belongsTo fields as join tables.
Data team consulted for best way to identify join tables. 
Test cases added from the issue reported.
Associated feature request:
https://github.com/aws-amplify/amplify-codegen/issues/543
=> fix: improve join table identification

pull_request_template.md
We want to raise the bar and encourage our standard processes in our GitHub repos
Use a modified PR template that matches expected contents/checks when submitting a PR
Open to feedback on this format. Making heavy use of the tasklist formatting since github renders them as checkboxes, but the overall completion counts are not useful since we'd only expect at least one check in the automated tests section instead of all checked.
Also, shifting emphasis onto github issues for tracking work related to this repo since I don't believe we want to link to internal/private ticketing systems here.
=> add new PR template with tasks for each required section

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/model-values.ts, packages/codegen-ui/example-schemas/forms/composite-dog-datastore-update-scalar.json, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/model-fields-configs.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/form-field.ts, packages/codegen-ui/lib/generate-form-definition/helpers/model-fields-configs.ts, packages/test-generator/integration-test-templates/cypress/e2e/form/DSCompositeDog-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/generate-spec.cy.ts, packages/test-generator/integration-test-templates/src/FormTests/DSCompositeDog.tsx, packages/test-generator/lib/forms/datastore-form-update-composite-dog-scalar.json, packages/test-generator/lib/forms/index.ts
Scalar fields, namely indices, associated with 1:1 relationships, do not map correctly to the primary keys of the related model.
1. Map the correct keys
2. Filter out duplicate options. In the case of composite keys, hash keys are allowed to be the same as those of other records. But rendering duplicate options causes a React error.
Also factored out logic for identifying model data fields.
Asana task.
Built out the E2E with the new form and tested.
=> chore: support scalar relationship fields

package-lock.json, packages/codegen-ui-react/lib/__tests__/__utils__/amplify-renderer-generator.ts, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/lib/__tests__/__utils__/mock-schemas.ts, packages/codegen-ui/lib/__tests__/generic-from-datastore.test.ts, packages/codegen-ui/lib/generic-from-datastore.ts, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json
We have an action item to switch to using introspection schema from the MIPR.
Yet, it would make us vulnerable to runtime errors to switch our types completely over to introspection schema because at least in Studio, we would still be using the MIPR until 1) the endpoint work for introspection schema is complete and 2) customers switch over to it.
Expand types for getting `GenericDataModel` to handle both MIPR and introspection schema.
Ops ticket in Asana.
- [] N/A
=> chore: expand types to include introspection schema

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/react-forms/__snapshots__/form-renderer-helper.test.ts.snap, packages/codegen-ui-react/lib/__tests__/react-forms/form-renderer-helper.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/all-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/event-handler-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/type-helper.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/typescript-type-map.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/utils/constants.ts, packages/test-generator/integration-test-templates/cypress/e2e/form/DSCompositeDog-spec.cy.ts, packages/test-generator/integration-test-templates/src/FormTests/DSCompositeDog.tsx
Allow customer's to use a composite key on an update form
The form now accepts a composite key
=> feat: init composite key property on update form

packages/codegen-ui/lib/types/bindings.ts
union type doesn't work with the aws sdk types
make operandType a string
Tests already exist.
=> fix: make operandType more generic

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/index.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/label-decorator.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/render-array-field.ts, packages/codegen-ui-react/lib/react-component-renderer.ts, packages/codegen-ui/example-schemas/forms/custom-with-array-field.json, packages/codegen-ui/example-schemas/forms/input-gallery-create.json, packages/codegen-ui/lib/__tests__/__utils__/basic-form-definition.ts, packages/codegen-ui/lib/__tests__/utils/form-component-metadata.test.ts, packages/codegen-ui/lib/generate-form-definition/generate-form-definition.ts, packages/codegen-ui/lib/types/form/fields.ts, packages/codegen-ui/lib/types/form/form-definition.ts, packages/codegen-ui/lib/types/form/form-metadata.ts, packages/codegen-ui/lib/types/form/index.ts, packages/codegen-ui/lib/types/form/style.ts, packages/codegen-ui/lib/utils/form-component-metadata.ts, packages/test-generator/integration-test-templates/cypress/e2e/form/CustomDog-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/form/CustomNestedJSON-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/utils/form.ts, packages/test-generator/integration-test-templates/src/FormTests/DSBidirectionalToy.tsx, packages/test-generator/lib/forms/custom-form-create-dog.json, packages/test-generator/lib/forms/custom-form-nested-json-create.json, packages/test-generator/lib/forms/datastore-form-create-all-supported-form-fields.json
Add configured `* or  - optional` to form label
Add `labelDecorator` property to field config in form schema
=> feat: add optional or required decorator on form labels

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui/example-schemas/collectionWithBinding.json, packages/codegen-ui/lib/__tests__/renderer-helper.test.ts, packages/codegen-ui/lib/renderer-helper.ts, packages/test-generator/integration-test-templates/cypress/e2e/generate-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/generated-components-spec.cy.ts, packages/test-generator/integration-test-templates/src/ComponentTests.tsx, packages/test-generator/lib/components/collections/collectionWithBetweenPredicate.json, packages/test-generator/lib/components/collections/index.ts
predicates with operator `between` are currently not supported because it requires 2 operands.
1. add a way to handle 2 operands
2. resolve `between` predicates into combined predicate of `le` and `ge`
Alternatives explored:
- Adding `operandList: string[]` to `StudioComponentPredicate` to handle multiple operands: was advised against bloating model.
- Changing the `createDataStorePredicate` helper to handle 2 operands: still an option. Breaking down the `between` predicate just avoided 1) submitting change to `amplify-ui` and 2) waiting for the release and 3) updating Studio w/ the release and updating CLI dep warning w/ the release
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
=> feat: support between predicates

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
Release for:
- Sev2 bug fix for colliding datamodel and variable name for update form
=> chore(release): v2.11.0

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui/example-schemas/datastore/car.json, packages/codegen-ui/example-schemas/forms/car-datastore-update.json, packages/codegen-ui/lib/__tests__/__utils__/mock-schemas.ts, packages/codegen-ui/lib/__tests__/generic-from-datastore.test.ts, packages/codegen-ui/lib/generic-from-datastore.ts
When a customer has 1:m relationship with `fields` defined on the relationship field of the parent, generic data schema is incorrectly mapped, so the child form does not correctly generate. See ` cars: [Car] @hasMany(fields: ["id"])` on
```
type Dealership @model {
id: ID!
name: String!
cars: [Car] @hasMany(fields: ["id"])
}
type Car @model {
id: ID!
name: String!
dealershipId: ID
dealership: Dealership @belongsTo(fields: ["dealershipId"])
}
```
Fix mapping
Manually tested both the child and parent forms.
=> chore: handle bidirectional 1:m with field defined on parent

packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/model-fields-configs.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/model-fields-configs.ts
We are encountering customers running into the error `Cannot find corresponding key for scalar relationship field`. It is technically correct to throw this as a service fault when we can't handle a schema. We handled one such case in this PR: https://github.com/aws-amplify/amplify-codegen-ui/pull/953.
But there may be other types of schemas we do not yet handle.
Mitigate the issue by setting a default that will handle all cases except custom primary keys instead of throwing.
Q: Aren't we just masking the issue and generating potentially broken forms?
A: Setting the default to `id` will handle all cases except CPKs. Even if the form is broken, customers would be able to use the generated form to update non-relationship fields.
- [] N/A - (provide a reason)
By submitting …
=> chore: stop throwing for unhandled relationship indexes

packages/test-generator/integration-test-templates/cypress/e2e/form/DSCar-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/form/DSDealership-spec.cy.ts
Integration tests for some datastore forms are failing due to the results taking too long to render for cypress.
Updating `cy.get('.results').then(...` to `cy.contains('.results', {desiredResult}).then(...` forces cypress to wait for results to render where we are expecting them to.
This pattern matches other datastore form tests where we don't have issues.
After the update, ran `npm run integ` locally and tests are consistently passing after several runs.
=> Update cypress get to contains for DS tests

packages/codegen-ui/lib/__tests__/generate-form-definition/generate-form-definition.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/defaults.ts, packages/codegen-ui/lib/generate-form-definition/helpers/field-type-map.ts, packages/codegen-ui/lib/generate-form-definition/helpers/form-field.ts, packages/codegen-ui/lib/types/form/form-definition-element.ts, packages/codegen-ui/lib/types/form/index.ts, packages/codegen-ui/lib/types/form/input-config.ts
To support new field type on form builder: FileUploaderField
=> feat: generate form definition with file uploader config

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/event-handler-props.ts, packages/codegen-ui-react/lib/react-required-dependency-provider.ts
The rendered StorageManager component is using incorrect prop name. 
onFileSuccess -> onUploadSuccess
Updating the prop name to onUploadSuccess
=> Updating StorageManager codegen prop onUploadSuccess

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/event-targets.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/form-state.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/utils/constants.ts, packages/codegen-ui-react/lib/utils/forms/storage-field-component.ts
Amplify UI does not us `s3Key` but `key` and it does not use `ref`
Change `s3Key` to `key` and remove ref.
=> fix: change key name and remove ref

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/event-handler-props.ts, packages/codegen-ui-react/lib/react-required-dependency-provider.ts, packages/codegen-ui-react/lib/utils/forms/storage-field-component.ts
- onUploadSuccess was not working
- onFileRemove was missing
- defaultFiles was hard-coded and also throwing when value was null
- change ui-react-storage recommendation to 1.0.1 - we thought they would have to rev to 1.0.2 but don't.
=> fix: change handlers and props for StorageField

.github/workflows/check.yml
we run integration tests that call yarn setup-dev. It's been failing at this step ([see example log](https://github.com/aws-amplify/amplify-codegen-ui/actions/runs/4619674637/jobs/8168733246)).
See this PR for context - https://github.com/aws-amplify/amplify-cli/pull/12389
=> fix: address yarn failures during check

packages/codegen-ui-react/lib/react-component-render-helper.ts, packages/codegen-ui-react/lib/utils/forms/storage-field-component.ts, packages/codegen-ui/lib/utils/form-to-component/map-form-definition-to-component.ts
Icon processing is broken because the schemas are saved with lower-cased `"object"` as the value type. We had added a condition that starts rendering this type as a string instead of an actual array.
Remove the condition and move it into the form-definition-to-component mapper instead. Testing added by the way of setting the type of that property to lower case "object"
=> fix: address icon regression

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui/example-schemas/primitives/IconPrimitiveWithLowerCasedType.json
The PR fixing icon regression did not have enough coverage: https://github.com/aws-amplify/amplify-codegen-ui/commit/d913b932b0edda5c148299d6ffe8d6dadbe72ac7
This adds coverage.
- [x ] Unit tests added/updated
=> test: add coverage for icon regression fix

packages/codegen-ui-react/lib/__tests__/react-forms/__snapshots__/form-renderer-helper.test.ts.snap, packages/codegen-ui-react/lib/__tests__/react-forms/form-renderer-helper.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/validation.ts
True, typescript-wise, `strValues` and `numValues` should be defined if they exist as keys on  `FieldValidationConfiguration`, but we just had a regression where the UI was passing in values like `strValues: null`, causing rendering errors.
Check that the value exists before further processing.
=> chore: improve runtime safety of validation builder

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/model-values.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/render-array-field.ts
When clicking on cancel in Autocomplete of relationship field, the default value prints undefined
change default to empty string
GitHub issue [](https://github.com/aws-amplify/amplify-studio/issues/809)
=> fix: autocomplete display value is undefined on cancel

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/utils/forms/storage-field-component.ts, packages/codegen-ui/example-schemas/forms/product-datastore-update-non-array.json
Fixing update form with storage field where existing files are not rendered. StorageManager component does not update with `defaultFiles` prop update.
Conditionally render after the record has been fetched.
=> fix: update form with storage field should render with existing files

packages/codegen-ui-react/lib/__tests__/react-studio-dependency-provider.test.ts, packages/codegen-ui-react/lib/react-required-dependency-provider.ts, packages/codegen-ui/lib/required-dependency-provider.ts
Messaging for requiring ui-react-storage dependency was showing up even for users that are not using StorageManager.
Make messaging conditional to only show for users who are using StorageManager.
Following up on CLI side to check if a user has StorageManager in their forms and pass the `hasStorageManager` boolean value.
=> fix: set conditional messaging for ui-react-storage

.circleci/config.yml
=> fix: upgrade node and pin lerna version in circleci

packages/codegen-ui-react/package.json, packages/codegen-ui/lib/__tests__/__utils__/introspection-schemas/schema-with-2-has-one.json, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/model-fields-configs.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/model-fields-configs.ts, packages/codegen-ui/package.json
If a customer has multiple hasOne relationships for the same model, we currently default to the first field. 
This adds an additional check to ensure that the field selected also uses the same key.
No
GitHub issue: N/A
=> fix(codegen-ui): fix multiple has one relationships

.circleci/config.yml, packages/codegen-ui-react/lib/utils/storage-manager.ts
Exporting processFile util function to be used in Amplify Studio UI Builder preview
=> feat: exporting processFile to be used in studio

packages/codegen-ui-react/lib/index.ts
export processFile at `lib/index` to be used by consumers
export processFile at `lib/index` to be used by consumers
=> chore: export processFile from lib/index

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/__utils__/amplify-renderer-generator.ts, packages/codegen-ui-react/lib/__tests__/imports/__snapshots__/import-collection.test.ts.snap, packages/codegen-ui-react/lib/__tests__/imports/import-collection.test.ts, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/amplify-ui-renderers/form.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/bidirectional-relationship.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/type-helper.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/imports/import-collection.ts, packages/codegen-ui-react/lib/imports/import-mapping.ts, packages/codegen-ui-react/lib/react-component-render-helper.ts, packages/codegen-ui-react/lib/react-index-studio-template-renderer.ts, packages/codegen-ui-react/lib/react-render-config.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui-react/lib/react-theme-studio-template-renderer.ts, packages/codegen-ui-react/lib/react-utils-studio-template-renderer.ts, packages/codegen-ui-react/lib/views/react-view-renderer.ts, packages/codegen-ui-react/lib/workflow/action.ts, packages/codegen-ui-react/lib/workflow/mutation.ts, packages/codegen-ui-react/package-lock.json, packages/codegen-ui/package-lock.json, packages/test-generator/lib/generators/TestGenerator.ts, packages/test-generator/package-lock.json
Customers who do not use DataStore are unable to build data-bound components
Codegen has been updated with the ability to conditionally generate components using GraphQL APIs rather than using the DataStore library.
The update for model imports carries the assumption that the GraphQL API types (default path /src/API.ts) has been generated in the customer's project. These have no functional impact on the output and are just to help establish strict types in the customer project. If customers have the ability to codegen GraphQL operations without these types we will need followup work to gracefully fall back on using the `any` type.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
=> feat: add graphql support for components

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/amplify-ui-renderers/amplify-form-renderer.ts, packages/codegen-ui-react/lib/amplify-ui-renderers/form.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/cta-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/index.ts, packages/codegen-ui-react/lib/forms/index.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts
Customers who do not use DataStore are not able to build create forms with GraphQL APIs.
Conditionally generate needed code for GraphQL APIs rather than using the DataStore library for create forms without relationships. Refactoring some of the DataStore specific functions to accommodate config to determine if the customer is using GraphQL. 
=> feat: add graphql support for create form

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/bidirectional-relationship.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/cta-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts, packages/codegen-ui-react/lib/imports/import-mapping.ts, packages/codegen-ui-react/lib/utils/graphql.ts, packages/codegen-ui-react/lib/workflow/action.ts, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json
We are importing API library with `import { API } from '@aws-amplify/api';` while Amplify docs use `import { API } from 'aws-amplify';`
There is a lot of duplicate code for creating the following codegen code:
```
API.graphql({
query: createTodo,
variables: {
input: {
modelFields
}
}
});
```
Update import to `aws-amplify` to align with Amplify docs.
Refactor GraphQL call expressions to one common function to cut down on duplicate code.
Import `pluralize` to pluralize model names for GraphQL list queries, this matches what is being done in `@aws-amplify/appsync-modelgen-plugin`
=> Update GraphQL API import and refactor GraphQL call expressions

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/__utils__/mock-data-schemas.ts, packages/codegen-ui-react/lib/__tests__/react-component-render-helper.test.ts, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/react-component-render-helper.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui/example-schemas/collectionWithBindingItemsName.json
comparing equality with filter operand as string returns false. 0 == '0'
Parse operand value when field type is a number
=> fix: parse operand value when field is number type

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts
GraphQL form unit tests don't have snapshots of declaration files.
Update `renderConfig` for GraphQL unit tests to render type declarations.
=> chore: add declaration snapshots

packages/codegen-ui-react/lib/__tests__/__snapshots__/react-theme-studio-template-renderer.test.ts.snap, packages/codegen-ui-react/lib/__tests__/react-theme-studio-template-renderer.test.ts, packages/codegen-ui-react/lib/react-theme-studio-template-renderer.ts
We aren't returning the declaration value in theme unlike other renderers
Returns the declaration value for theme
=> fix: return theme declaration file from render func

.github/workflows/check.yml, package.json
Our `amplify-cli-tests` action is failing to build amplify-cli.
`lerna bootstrap` was using lerna v7.0.0 where `bootstrap` was deprecated, switched to running through an npm script so we can continue using lerna v6.4.1
=> chore: update cli check

packages/codegen-ui-react/lib/__tests__/__utils__/amplify-renderer-generator.ts, packages/codegen-ui-react/lib/imports/import-collection.ts, packages/codegen-ui-react/lib/react-render-config.ts
the helper provided by `amplify-codegen` provides separate path values for each graphql operation type rather than just returning a common base path. This allows for additional flexibility in the future if there's ever a reason to allow operations to be located on different paths rather than always implied to be in neighboring files in the same directory, and also allows for file names to be customized in the future if required.
Update the GraphQL config model to accept explicit file paths for each operation type rather than working off of naming conventions and concatenation based on a given base path.
=> feat: update GraphqlRenderConfig to use separate props for each file path

scripts/integ-setup.bat, scripts/integ-setup.sh
Seems like a regression was introduced in Cypress v12.15.0, `functional-tests` are failing with the following error message for all specs:
```
CypressError: `cy.task()` must only be invoked from the spec file or support file.
```
Set Cypress version to v12.14.0.
Once Cypress addresses the issue this can be removed to ensure we are using the latest Cypress for integration tests.
=> chore: add specific cypress version to fix 12.15.0 bug

scripts/integ-setup.bat, scripts/integ-setup.sh
`functional-tests` are failing because of Cypress regression.
Merge commit from #1028.
=> Update from main

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/amplify-ui-renderers/amplify-renderer.ts, packages/codegen-ui-react/lib/amplify-ui-renderers/collection.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/helpers/index.ts, packages/codegen-ui-react/lib/imports/import-collection.ts, packages/codegen-ui-react/lib/imports/import-mapping.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui-react/lib/views/react-view-renderer.ts, packages/codegen-ui/lib/types/bindings.ts
Customers who do not use DataStore are not able to create collections with GraphQL APIs.
Conditionally generate needed code for GraphQL APIs rather than using the DataStore library for collections.
=> feat: graphql support for collections

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts, packages/codegen-ui-react/lib/utils/graphql.ts, packages/codegen-ui/example-schemas/datastore/relationships/has-many-comment.json, packages/codegen-ui/example-schemas/datastore/relationships/many-to-many-class.json, packages/codegen-ui/example-schemas/forms/relationships/update-class.json, packages/codegen-ui/example-schemas/forms/relationships/update-comment.json
Note diff in existing datastore forms, 
Verified unit test snapshot to match spec
=> feat: [GraphQL] update form with relationship

pull_request_template.md
some minor items that we can't/don't lint for can go through PR unnoticed.
add new PR tasks as a reminder to devs and reviewers to confirm that submitted changes are compliant.
=> chore: add housekeeping items to PR template

packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts, packages/codegen-ui-react/lib/utils/graphql.ts, packages/codegen-ui/example-schemas/bindings/data/componentWithDataStoreCreateActionBinding.json, packages/codegen-ui/lib/__tests__/__utils__/load-schema.ts, packages/codegen-ui/lib/__tests__/utils/data-binding-utils.test.ts, packages/codegen-ui/lib/utils/data-binding-utils.ts, packages/test-generator/lib/models/schema.ts, scripts/integ-templates.sh
Multiple projects need the ability to identify if a form or component requires a working data API in order to be functional once generated.
Exporting two new helpers to identify this dependency, as the associated logic has some nuance and should be implemented in one central package.
=> feat: add helpers to identify api dependencies

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/type-helper.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/imports/import-collection.ts, packages/codegen-ui-react/lib/utils/graphql.ts
if types file is undefined in customer's app, it is importing graphql model types from undefined module
Remove empty/undefined modules from import collection and change graphQL model type to any
=> fix: remove type import if no graphql types file

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/utils/graphql.ts
missing plural items in autocomplete data fetch
add 's'
GitHub issue:
=> fix: plural items property in autocomplete data query

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/__utils__/amplify-renderer-generator.ts, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/react-render-config.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui-react/lib/utils/graphql.ts, packages/codegen-ui/lib/errors/error-transformer.ts, packages/codegen-ui/lib/errors/error-types.ts
Forms and components requiring a data API should not be generated if there is no API configuration
add `NoApi` configuration type and throw new error if the item being generated has a data dependency while the `NoApi` configuration is used.
GitHub issue:
=> feat: add NoApi configuration and validation for data dependency

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts
Unlinking child records in a hasMany relationship is currently using the delete operation for GraphQL forms. This is a destructive action and does not align with what is done on DataStore forms. Furthermore the form validation suggests the intended action is an update as it checks if the parent id field is required on the child.
Update codegen to generate requests using the update operation to clear the parent reference on a child record.
GitHub issue:
=> fix: change GraphQL unlink to use update action instead of delete

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/utils/graphql.ts
Autocomplete data property access used property name based on field name
should be based on related model name
=> fix: change autocomplete data access property to related model name

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/form-state.ts
In CMS, if the customer creates an empty record and then reopens the record, 'null' is displayed for JSON fields. 
Adds a condition to avoid stringifying `null`. This change also applies to `metadata` and `nonModelField` types as well as `json`.
=> fix: fields with json type display 'null'

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/cta-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/utils/graphql.ts, packages/codegen-ui/example-schemas/forms/relationships/update-movie.json, packages/codegen-ui/example-schemas/models/composite-key-movie.json
1. GraphQL implementation does not correctly query records from tables with composite primary keys.
2. GraphQL implementation does not correctly delete records from join tables.
3. GraphQL implementation does not correctly create join table records.
1. identify when model uses composite keys and conditionally render a spread operation on the id property rather than use a value assignment
2. correct input nested in input, access and use the id property on the record to be deleted rather than providing the full record
3. change from providing full models to API like in DataStore, and update to sending primary key values for the related table records
GitHub issue:
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
=> fix: bugfixes for GraphQL composite key querying and join table deletion

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/utils/graphql.ts
Form codegen does not properly query against join tables for many:many relationships when using GraphQL
Implement proper querying using the indexed query assumed to be in the customer project
GitHub issue:
=> feat: implement graphql querying for join tables

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts, packages/codegen-ui-react/lib/utils/graphql.ts, packages/codegen-ui/example-schemas/forms/post-graphql-create.json, packages/codegen-ui/example-schemas/forms/post-graphql-update.json
Remove query with index for 1:many relationship parent
=> fix: remove indexes query from one to many parent update

.github/workflows/check.yml, packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/cta-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/render-array-field.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/react-component-renderer.ts, packages/codegen-ui-react/lib/utils/graphql.ts, packages/codegen-ui/example-schemas/datastore/relationships/has-many-comment-no-belongsTo.json, packages/codegen-ui/example-schemas/forms/relationships/update-comment-no-belongsTo.json
The link from a child to a parent is always implemented with an id field on the child holding the id of its parent, customers can optionally annotate this field with `@belongsTo` to make the relationship bidirectional. For forms, we always want to behave as if the relationship is bidirectional, mainly to give us the ability to utilize the autocomplete control to update the parent id.
Add conditional logic for GraphQL to add bidirectional abilities for forms.
Also adds a step to our Github actions to upload Cypress videos if Cypress tests fail in order to gather more insight when debugging failing tests.
GitHub issue:
=> feat: handle parent relationship without belongsTo for GraphQL

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/utils/graphql.ts
Autocomplete dropdown is empty on load
Query related records on form load
=> fix: fetch all related records initially

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/all-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/event-handler-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/model-values.ts, packages/codegen-ui-react/lib/helpers/index.ts, packages/codegen-ui/example-schemas/datastore/dog-owner-required.json
There are inconsistencies in casing and using model name instead of field name for a couple variables used for the Autocomplete control. This causes errors such as: `_____ is not defined`.
Update variables used in `options` and `onSelect` to match the appropriate local state.
Update `dog-owner-required` schema to represent lowercase model fields to ensure we match casing from schema.
GitHub issue:
=> fix: update variables to match local state

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/cta-props.ts
* properties are missing from create/update requests when non-required values are empty
* all-whitespace values are being trimmed on save but not when validated or passed into a customer's `onSubmit` callback.
* update the empty string replacement operation to replace with `null` instead of `undefined` which was getting stripped when making the API request.
* remove string trimming when checking if a string is empty
GitHub issue:
=> fix: remove trim on empty string replace, use null for replacement value

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/amplify-ui-renderers/form.ts
GraphQL calls return an array of errors due to the APIs ability to batch requests. As a result, errors come back in an unexpected format and those messages are not sent to the customer's onError callback
Add an extra step to map and join error messages when using GraphQL and pass this to the customer's onError callback.
GitHub issue:
=> fix: consolidate batch errors when using GraphQL

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/cta-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts, packages/codegen-ui/example-schemas/forms/cpk-teacher-datastore-create.json, packages/codegen-ui/example-schemas/forms/relationships/create-movie.json
Creating a record with child throws with the following error: `The variables input contains a field that is not defined for input object type '_____'`
Get correct response data from create parent GraphQL statement and change inputs passed to update child GraphQL statement.
GitHub issue:
=> fix: update create parent and update child graphql expressions

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts
update forms are generated with import statements for non-existent join table query
pluralize the join table name when building the query name to get the correct import
GitHub issue:
=> fix: pluralize table name when building join table index query

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts
BelongsTo field does not exist as an input for update related model GraphQL expressions yet we are feeding it as an input.
Remove BelongsTo field for related models for create forms with hasMany and BelongsTo relationships.
GitHub issue:
=> fix: remove belongsto field for update related model expression

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/parse-fields.ts, packages/codegen-ui/example-schemas/models/comment-with-postID/forms/CommentCreateForm.json, packages/codegen-ui/example-schemas/models/comment-with-postID/forms/CommentUpdateForm.json, packages/codegen-ui/example-schemas/models/comment-with-postID/schema.graphql, packages/codegen-ui/example-schemas/models/comment-with-postID/schema.json
For update forms using parent id without belongsTo, parent id is not being passed into the update request.
Add parent id to the update request.
GitHub issue:
=> fix: add parent id to update requests

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/cta-props.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui/example-schemas/models/custom-key-model/forms/CustomKeyModelUpdateForm.json, packages/codegen-ui/example-schemas/models/custom-key-model/schema.graphql, packages/codegen-ui/example-schemas/models/custom-key-model/schema.json
For models using a custom primary key, the update form incorrectly uses `id` as the key field when fetching the record
update form generation to use the single primary key of a model as the variable for fetching, rather than hardcoding as `id`
GitHub issue:
=> fix: use custom primary key name when fetching record for update form

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/render-array-field.ts, packages/codegen-ui-react/lib/utils/forms/array-field-component.ts
Fix [#961 
](https://github.com/aws-amplify/amplify-studio/issues/961)
We should not disabled the `Add` button when validation fails and instead invoke `runValidation` again when adding a new item to refresh the error state. That way a user will be able to add the missing field by clicking the button straight without having to clear the input or type in something to refresh before adding a value.
GitHub issue:
=> fix: fix add button disabled state on validation failure

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/form-state.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/model-values.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/render-array-field.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui/example-schemas/models/comment-with-postID/forms/PostUpdateForm.json, packages/codegen-ui/example-schemas/models/custom-key-model/forms/ChildItemUpdateForm.json
For forms with GraphQL, scalar relationship autocomplete fields can load with the badge text as `undefined`.
Store relationship data in local state for badge text with the autocomplete options as a fallback for when a customer selects an autocomplete option.
GitHub issue:
=> fix: store selected relationship data for scalar fields

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/render-array-field.ts
The form throws when changing selection of a record for the autocomplete field.
Wrap value for setting local state in an array.
GitHub issue:
=> fix: wrap set state with array expression

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/react-studio-template-renderer.ts
collection components are generating GraphQL requests using queries that do not exist in the customer's AppSync API
Collections need to be updated to operate on the same assumptions as forms and rely on the main record's query already having their child collections populated.
GitHub issue:
=> fix: collection components should not directly query for child collection data

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/model-values.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/render-array-field.ts
In certain situations when starting to update a selected record in an autocomplete field and canceling without updating selection, selected record state becomes `undefined`.
Conditionally set selected record state if setting a new value, otherwise it will keep its original value.
Reordered which state to try to find a matching record for badge text and field value.
GitHub issue:
=> fix: conditionally set selected record state

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/bidirectional-relationship.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/cta-props.ts
When submitting update forms with bidirectional relationships, the form throws with an error message: `The variables input contains a field that is not defined for input object type ______`.
Change inputs for update GraphQL calls for linking and unlinking records.
GitHub issue:
=> fix: update inputs for linking and unlinking bidirectional relationships

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts
Declaration file generating model type when there is none for graphql with no types path
change model type to any
GitHub issue:
yes
=> fix: change model type to any if no graphql types

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/react-studio-template-renderer.ts
Response from list model had `items` property access which nextToken referenced. items and nextToken properties are siblings.
move items property access off of result variable
local app
=> fix: move graphql collection 'items' property access off of result variable

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/amplify-ui-renderers/collection.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui/example-schemas/authorCollectionComponent.json
Graphql collection is using a constant page size of 4.
Use the itemsPerPage component property, fallback to 6
local app
=> fix: use itemesPerPage for graphql collection query limit

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/amplify-ui-renderers/collection.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts
The implementation for collections using GraphQL did not include support for not having the collection be paginated.
Add a component level variable for pagination and update querying/rendering logic to incorporate checking this value
As part of this implementation, the `isPaginated` property on the underlying collection component is now always set where previously the property was only referenced if the component was configured to have pagination.
GitHub issue:
=> fix: add missing support for GraphQL collections without pagination

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui-react/lib/utils/graphql.ts, packages/test-generator/integration-test-templates/cypress/scripts/generateCoverageSummary.mjs
Update forms that include fields for custom type properties can fail on submission due to the inclusion of a `__typename` property.
Query generation cannot be updated at this time so form codgen is being updated to strip the `__typename` properties from the queries before execution.
GitHub issue:
=> fix: exclude __typename metadata property when querying for form data

packages/codegen-ui-react/lib/react-render-config.ts
We need to generate backwards compatible code to support both v5 and v6 amplify js libraries.
Update the render config to take in the current amplify project's dependencies that are required to determine which code to generate for the given project.
GitHub issue:
=> chore: add dependencies to render config type

packages/codegen-ui-react/lib/__tests__/helpers/amplify-js-versioning.test.ts, packages/codegen-ui-react/lib/__tests__/react-studio-dependency-provider.test.ts, packages/codegen-ui-react/lib/helpers/amplify-js-versioning.ts, packages/codegen-ui-react/lib/imports/import-mapping.ts, packages/codegen-ui-react/lib/react-required-dependency-provider.ts, packages/codegen-ui-react/lib/utils/constants.ts, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/lib/required-dependency-provider.ts
We need to add and update our current versioning helpers to eventually support amplify js v6 breaking changes.
Update the required dependency provider.
Add helper functions to know which version of amplify js v6 to render.
GitHub issue:
=> feat: update dependency versioning helpers

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
We need to release the version helpers so that the amplify cli can use them to know which warning messages to show the user if they need to install amplify js v5 or v6 packages.
This release has the changes needed.
GitHub issue:
=> chore(release): v2.16.0

packages/codegen-ui-react/lib/index.ts
This helper is used in external packages to derive the correct declaration filename of a generated component file.
GitHub issue:
=> feat: export declaration filename helper

packages/codegen-ui-react/lib/utils-file-functions/hooks/useAuthSignoutAction.ts, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json
- Add aws-ampilify and datastore to optional dependency
- Remove dependency on amplify auth type
GitHub issue:
=> fix: add datastore to optional dependency

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts
For graphql many many relationships, the onSubmit function has a reduce function to update the related model. This callback function was making a reference to the actual model instead of the reduce callback's parameter. One was lower case and the other was title cased.
Use the same value that's being used to create the callbacks arguments.
No. 
GitHub issue:
=> fix: join table related model name using incorrect casing

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/event-handler-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/form-state.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/model-values.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/render-array-field.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts
There were errors when trying to reference a value in a callback function where the value was undefined because it was not referencing the correct variable name that was defined in the variable statements part of the components.
I updated how the reference was created so it is referencing the correct var name.
In general I worked on simplifying the code of creating the `Records` value name to make sure it's consistent across each use case that needs that variable name.
GitHub issue:
I updates all the snapshots and went through all the snapshots changes to make sure the references to all the name changes were pointing to the correct variable.
=> Fix undefined ref errors in {val}ToLinkMap callbacks

.github/workflows/canaries.yml, .github/workflows/check.yml, packages/codegen-ui-react/lib/helpers/amplify-js-versioning.ts, packages/test-generator/e2e-test-templates-amplify-js-v6/.eslintrc.js, packages/test-generator/e2e-test-templates-amplify-js-v6/cypress.config.js, packages/test-generator/e2e-test-templates-amplify-js-v6/cypress/.eslintrc.js, packages/test-generator/e2e-test-templates-amplify-js-v6/cypress/e2e/e2e-tests.cy.js, packages/test-generator/e2e-test-templates-amplify-js-v6/src/App.js, packages/test-generator/lib/generators/GenerateTestApp.ts, packages/test-generator/package-lock.json, packages/test-generator/package.json, scripts/integ-setup.bat, scripts/integ-setup.sh, scripts/integ-templates.sh
Amplify JS UI React just moved v6 to latest and we need to render v6 code as latest.
Update v6 feature flag
GitHub issue:
=> feat: move amplify js v6 to latest

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/__tests__/utils/__snapshots__/render-util-functions.test.ts.snap, packages/codegen-ui-react/lib/imports/import-mapping.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui-react/lib/react-utils-studio-template-renderer.ts, packages/codegen-ui-react/lib/utils-file-functions/hooks/index.ts, packages/codegen-ui-react/lib/utils-file-functions/hooks/useAuth.ts
We need to migrate the useAuth hook for v6
Migrate it over
GitHub issue:
=> fix: migrate useAuth hook for v6

.github/workflows/canaries.yml
Adding more tests for v6
Add the beta cli test that runs as a canary
GitHub issue:
=> fix: add amplify js v6 beta canary

packages/codegen-ui-react/lib/__tests__/__utils__/amplify-renderer-generator.ts, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/imports/import-collection.ts, packages/codegen-ui/example-schemas/datastore/games.json, packages/codegen-ui/example-schemas/forms/games.json
If a customer had an import for their generated component that was the same as a primitive component name e.g. "Text" it was not being aliased.
Add a check to see if the imported name is a primitive component.
GitHub issue:
unit test
=> fix: check if import name is a primitive and needs aliasing

packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/amplify-ui-renderers/customComponent.ts, packages/codegen-ui/example-schemas/components/footerWithCustomButton.json
References to custom components that have been aliased as part of the Figma import are not being generated with the correct component names or import paths.
Update custom component handling to use the non-aliased component name for imports instead of the node name, which matches the codegen output for the custom component itself.
GitHub issue:
=> fix: use non-aliased name when importing custom components

codegen-ui-golden-files/lib/react/forms/datastore-create-form-with-belongs-to/MemberCreateForm.jsx, codegen-ui-golden-files/lib/react/forms/datastore-update-form-with-has-many-relationship/SchoolUpdateForm.jsx, commitlint.config.js
Fix [code scanning alerts](https://github.com/aws-amplify/amplify-codegen-ui/security/code-scanning/44) and add `deps-dev` to allow dev dependencies update from dependabot
GitHub issue:
=> fix: fix code scanning alerts

scripts/integ-setup.bat, scripts/integ-setup.sh, scripts/integ-setupv6.bat, scripts/integ-setupv6.sh
CI runs were consistently failing due to a change in the @cypress/code-coverage package adding an optional chain for null safety, but results in a `Module parse failed: Unexpected token` error.
https://github.com/cypress-io/code-coverage/pull/822
Updating to a more recent version of Cypress resolves the module parse error as it likely enables compatibility for optional chaining.
GitHub issue:
=> chore: update Cypress dependency
