.github/workflows/check.yml, README.md, codecov.yaml
=> ci: add codecov

.circleci/config.yml
comments were added to the same line
=> ci: remove comments from pre release

packages/codegen-ui-react/lib/__tests__/react-studio-dependency-provider.test.ts, packages/codegen-ui-react/lib/react-required-dependency-provider.ts, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/index.ts, packages/codegen-ui/lib/required-dependency-provider.ts
Cherry-picking so that we can release with the supported version flag on Monday.
=> chore: cherry-pick https://github.com/aws-amplify/amplify-codegen-ui/pull/302 into main

packages/codegen-ui-react/lib/react-component-render-helper.ts, packages/codegen-ui/lib/types/studio-types.ts
Adding strong type for operator to accept only certain operator string values
=> Operator type

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/__tests__/studio-ui-json/complexTest10.json, packages/codegen-ui-react/lib/__tests__/studio-ui-json/complexTest11.json, packages/test-generator/integration-test-templates/cypress/integration/complex-spec.ts, packages/test-generator/integration-test-templates/cypress/integration/generate-spec.ts, packages/test-generator/integration-test-templates/src/ComplexTests.tsx, packages/test-generator/lib/components/complex-tests/complexTest10.json, packages/test-generator/lib/components/complex-tests/complexTest11.json, packages/test-generator/lib/components/complex-tests/index.ts
add additional complex tests using the studio payload from figma golden file(Picked two that look "complex")
add additional two complex tests, and assert various components in the complex component 
=> test: add additional complex tests

packages/test-generator/integration-test-templates/cypress/integration/generate-spec.ts, packages/test-generator/integration-test-templates/cypress/integration/generated-components-spec.ts, packages/test-generator/integration-test-templates/src/ComponentTests.tsx, packages/test-generator/lib/components/collections/index.ts, packages/test-generator/lib/components/collections/searchableCollection.json
N/A
Ensure we have test coverage for all major features in collections, including search, pagination, and filtering.
=> chore: add integration test for searchable collections

.github/workflows/check.yml
=> chore: catch develop up with main

.github/workflows/check.yml
=> Catch up q1 release

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/__tests__/studio-ui-json/workflow/dataStoreCreateAction.json, packages/codegen-ui-react/lib/action.ts
Adds stub for DataStoreCreateItem action but does not fully implement
=> feat: add special case for fields and model action parameters

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/react-component-render-helper.ts, packages/codegen-ui-react/lib/workflow/mutation.ts, packages/codegen-ui/example-schemas/workflow/setStateWithoutInitialValue.json, packages/codegen-ui/example-schemas/workflow/updateVisibility.json
N/A
Adding a few additional test cases around non-label fields, and materially adding support for uninitialized mutation elements.
=> chore: add additional test cases

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/imports/import-mapping.ts, packages/codegen-ui-react/lib/react-component-renderer.ts, packages/codegen-ui-react/lib/react-component-with-children-renderer.ts, packages/test-generator/integration-test-templates/cypress.json, packages/test-generator/integration-test-templates/cypress/integration/generate-spec.ts, packages/test-generator/integration-test-templates/cypress/integration/workflow-spec.ts, packages/test-generator/integration-test-templates/src/WorkflowTests.tsx, packages/test-generator/integration-test-templates/src/mock-helpers.js, packages/test-generator/lib/components/collections/index.ts, packages/test-generator/lib/components/collections/simpleUserCollection.json, packages/test-generator/lib/components/workflow/authSignOutActions.json, packages/test-generator/lib/components/workflow/buttonsToggleState.json, packages/test-generator/lib/components/workflow/internalMutation.json, packages/test-generator/lib/components/workflow/mutationWithSyntheticProp.json, packages/test-generator/lib/components/workflow/navigationActions.json, packages/test-generator/lib/components/workflow/setStateWithoutInitialValue.json, packages/test-generator/lib/components/workflow/updateVisibility.json, packages/test-generator/lib/generators/GenerateTestApp.ts, scripts/integ-setup.bat, scripts/integ-setup.sh
N/A
Adding e2e tests for ui hooks implemented in `actions` branch.
=> chore: add e2e tests for mutations, auth, and navigation

package-lock.json, packages/codegen-ui-react/lib/workflow/action.ts, packages/codegen-ui/example-schemas/workflow/anchorNavigationAction.json, packages/codegen-ui/example-schemas/workflow/dataStoreCreateItem.json, packages/codegen-ui/example-schemas/workflow/dataStoreDeleteItem.json, packages/codegen-ui/example-schemas/workflow/dataStoreUpdateItem.json, packages/codegen-ui/example-schemas/workflow/form.json, packages/codegen-ui/example-schemas/workflow/hardNavigationAction.json, packages/codegen-ui/example-schemas/workflow/newTabNavigationAction.json, packages/codegen-ui/example-schemas/workflow/reloadNavigationAction.json, packages/test-generator/lib/components/workflow/dataStoreActions.json, packages/test-generator/lib/components/workflow/formWithState.json, packages/test-generator/lib/components/workflow/navigationActions.json
N/A
External model and internal enums had drifted, bringing them back inline.
=> fix: bringing action names back inline with external model

.husky/pre-commit
feat: add git secrets check and scan 
Adding git secrets check and enabling scan to prevent from committing passwords and other sensitive information to a git repository.
=> feat: add git secrets check and scan

scripts/integ-setup.bat, scripts/integ-setup.sh
N/A
* flip back to `@latest` branch of ui now that hooks are released
=> chore: flip back to @latest branch of ui now that hooks are released

packages/test-generator/integration-test-templates/cypress/integration/generate-spec.ts, packages/test-generator/integration-test-templates/cypress/integration/two-way-binding-spec.ts, packages/test-generator/integration-test-templates/src/App.tsx, packages/test-generator/integration-test-templates/src/TwoWayBindingTests.tsx, packages/test-generator/lib/components/workflow/index.ts, packages/test-generator/lib/components/workflow/twoWayBindings.json
N/A
Adding tests to verify that two-way binding of all form fields works.
=> feat: adding form with actions example

packages/test-generator/integration-test-templates/cypress/integration/generate-spec.ts, packages/test-generator/integration-test-templates/cypress/integration/workflow-spec.ts, packages/test-generator/integration-test-templates/src/WorkflowTests.tsx, packages/test-generator/integration-test-templates/src/models/index.d.ts, packages/test-generator/integration-test-templates/src/models/index.js, packages/test-generator/integration-test-templates/src/models/schema.js, packages/test-generator/lib/components/workflow/createModelWithComplexTypes.json, packages/test-generator/lib/components/workflow/index.ts
N/A
add functional test with complex serialized datastore items with nested object types and lists.
=> chore: add functional test with complex serialized datastore items

packages/codegen-ui-react/lib/react-required-dependency-provider.ts
N/A
* Update to the next expected version we'll support.
=> chore: update required ui-react dependency

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/amplify-ui-renderers/__snapshots__/primitives.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/amplify-ui-renderers/amplify-renderer.ts, packages/codegen-ui-react/lib/primitive.ts, packages/codegen-ui/example-schemas/primitives/TextAreaFieldPrimitive.json, packages/codegen-ui/example-schemas/workflow/twoWayBindings.json, packages/test-generator/integration-test-templates/cypress/integration/generate-spec.ts, packages/test-generator/integration-test-templates/cypress/integration/primitives-spec.ts, packages/test-generator/integration-test-templates/cypress/integration/two-way-binding-spec.ts, packages/test-generator/integration-test-templates/src/PrimitivesTests.tsx, packages/test-generator/integration-test-templates/src/TwoWayBindingTests.tsx, packages/test-generator/lib/components/primitives/TextAreaFieldPrimitive.json, packages/test-generator/lib/components/primitives/index.ts, packages/test-generator/lib/components/workflow/twoWayBindings.json, scripts/integ-setup.bat, scripts/integ-setup.sh
N/A
* Add `TextAreaField` primitive.
* Remove top-level multiline support from `TextField`.
=> feat: add TextAreaField primitive

CHANGELOG.md, lerna.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
N/A
Releasing Codegen Library v2.
=> chore(release): v2.0.0

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/workflow/action.test.ts, packages/codegen-ui-react/lib/name-replacements.ts, packages/codegen-ui-react/lib/react-component-render-helper.ts
Started with ascii characters, but could easily be expanded.
=> feat: replace non-alpha characters with description

CHANGELOG.md, lerna.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.1.1

.github/CODEOWNERS
Updating codeowner info so all future reviews require 1 review from the studio uibuilder team.
=> chore: update codeowner as part of library handoff

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/react-studio-template-renderer.ts
=> fix: remove hook from conditional statement

packages/codegen-ui-react/lib/react-required-dependency-provider.ts
@aws-amplify/amplify-ui recently hotfixed the ui-react package. Updating our provider to give the latest version number.
=> chore: update ReactRequiredDependencyProvider to return latest version of ui-react

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/react-studio-template-renderer-helper.test.ts, packages/codegen-ui-react/lib/react-studio-template-renderer-helper.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/test-generator/integration-test-templates/src/WorkflowTests.tsx
Remove .jsx extension from declaration file ext
=> fix: remove jsx ext from declaration file ext

package-lock.json, package.json, packages/codegen-ui-react/package-lock.json, packages/codegen-ui/package-lock.json, packages/test-generator/package-lock.json
=> chore: types and codegen/ui depedency updates

.github/workflows/check.yml, .gitignore, packages/codegen-ui-react/package.json
- Fix the CLI test workflow
- Update Peer Dependencies for `codegen-ui-react`
- Update gitignore to include lerna packed tgz files
=> chore: update cli setup flow and update react peerDep

CHANGELOG.md, lerna.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.2.1

packages/codegen-ui/lib/__tests__/common-component-renderer.test.ts, packages/codegen-ui/lib/types/properties.ts, packages/codegen-ui/lib/types/string-format.ts
**Changes**
Adding string formatting type to be used by UI Library and by codegen string formatter feature
Asana ticket: [link](https://app.asana.com/0/1202399589110734/1202453065842783)
=> feat: adding string format types in lib

packages/codegen-ui-react/lib/amplify-ui-renderers/amplify-form-renderer.ts, packages/codegen-ui-react/lib/amplify-ui-renderers/form.ts, packages/codegen-ui-react/lib/workflow/events.ts, packages/codegen-ui-react/tsconfig.json, packages/codegen-ui/lib/__tests__/generate-form-definition/form-to-component.test.ts, packages/codegen-ui/lib/__tests__/generate-form-definition/index.test.ts, packages/codegen-ui/lib/generate-form-definition/form-to-component.ts, packages/codegen-ui/lib/generate-form-definition/index.ts, packages/codegen-ui/lib/types/events.ts, packages/codegen-ui/lib/types/form/index.ts, packages/codegen-ui/tsconfig.json
- add form renderer class
- add amplify form renderer class
=> feat: add base form renderer and amplify form renderer classes

packages/codegen-ui/lib/__tests__/string-formatter.test.ts, packages/codegen-ui/lib/types/string-format.ts, packages/codegen-ui/lib/utils/index.ts, packages/codegen-ui/lib/utils/string-formatter.ts, packages/codegen-ui/tsconfig.json
*Changes:*
* Fixed typo for library type
* Added util formatters and tests
=> feat: string formatter util functions

packages/codegen-ui/lib/__tests__/string-formatter.test.ts, packages/codegen-ui/lib/types/string-format.ts, packages/codegen-ui/lib/utils/string-formatter.ts
*Changes:*
* nullish string handling for our JS customers
* optional enum type to use for formatting args
=> fix: optional enum type and nullish handling

packages/codegen-ui/lib/types/form/fields.ts, packages/codegen-ui/lib/types/form/form-validation.ts
- Adds validation types for Form field configuration
=> chore: add validation field types for forms

packages/codegen-ui-react/lib/react-required-dependency-provider.ts
Bump recommended version of ui-react to ^3.10.0 so customers can pass in overrides of any type.
=> chore: rev recommended version of ui-react

CHANGELOG.md, lerna.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.3.0

CHANGELOG.md, lerna.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
- Fix recommended ui-react version: is now ^3.1.0
=> chore(release): v2.3.1

packages/codegen-ui-react/lib/__tests__/react-theme-studio-template-renderer.test.ts, packages/codegen-ui-react/package-lock.json, packages/codegen-ui/package-lock.json, packages/test-generator/package-lock.json
=> chore: pkg lock update

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/amplify-ui-renderers/form.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/react-utils-studio-template-renderer.ts, packages/codegen-ui-react/lib/utils/forms/validation.ts, packages/codegen-ui/lib/types/form/form-metadata.ts, packages/codegen-ui/lib/utils/form-component-metadata.ts, packages/codegen-ui/lib/utils/string-formatter.ts, packages/test-generator/integration-test-templates/cypress/e2e/generate-spec.cy.ts, packages/test-generator/lib/forms/basic-form-create.json, packages/test-generator/lib/forms/index.ts, packages/test-generator/lib/generators/BrowserTestGenerator.ts, packages/test-generator/lib/generators/NodeTestGenerator.ts, packages/test-generator/lib/generators/TestGenerator.ts
- Add utils file renderer
- Refactor validation function to use ts factory to conform to render templating
- Update test generators to include forms and utils rendering
- @kpranoto-aws : remove locale dependency on date formatting
- 
=> Render form utils and add forms to index file

packages/test-generator/integration-test-templates/cypress/e2e/primitives-spec.cy.ts
=> chore: update primitive test for SliderField

package-lock.json, packages/codegen-ui/lib/__tests__/__utils__/mock-schemas.ts, packages/codegen-ui/lib/generate-form-definition/form-to-component.ts, packages/codegen-ui/lib/generic-from-datastore.ts, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json
=> chore: move datastore to devDep for types & security pkg updates

CHANGELOG.md, lerna.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.3.2

packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/form-field.test.ts, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/model-fields-configs.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/defaults.ts, packages/codegen-ui/lib/generate-form-definition/helpers/field-type-map.ts, packages/codegen-ui/lib/generate-form-definition/helpers/form-field.ts, packages/codegen-ui/lib/generate-form-definition/helpers/mapper-utils.ts, packages/codegen-ui/lib/generate-form-definition/helpers/model-fields-configs.ts, packages/codegen-ui/lib/generate-form-definition/index.ts, packages/codegen-ui/lib/types/form/form-definition-element.ts, packages/codegen-ui/lib/types/form/form-definition.ts, packages/codegen-ui/lib/types/form/index.ts, packages/codegen-ui/lib/types/form/input-config.ts
1. Change shape of valueMappings - peer reviewed
2. generate valueMappings from Enums
3. Merge auto-generated valueMappings and overrides
=> chore: add valueMappings to forms

packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/form-field.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/defaults.ts
Change copy of the default value mappings
=> chore: change default value mappings

packages/codegen-ui/lib/types/form/index.ts
=> chore: update studio form type

packages/test-generator/integration-test-templates/cypress/e2e/primitives-spec.cy.ts
Update pagination primitive test
https://github.com/aws-amplify/amplify-ui/commit/5ffdc40a0ae45c8d1554e53e6b6a085231e6c34c#diff-1a12234c0099acb3ed6184c297cb7f89091451b85333c48c177706551497325cL95
=> chore: update pagination label in test

packages/codegen-ui/lib/types/view/style.ts, packages/codegen-ui/lib/types/view/view.ts
update types for views to use string primitives instead of the String class.
=> chore: update view types to use string primitives

packages/codegen-ui/lib/__tests__/generate-view-definition/generate-table-definition.test.ts, packages/codegen-ui/lib/__tests__/generate-view-definition/order-filter-columns.test.ts, packages/codegen-ui/lib/generate-view-definition/generate-table-definition.ts, packages/codegen-ui/lib/generate-view-definition/helpers/index.ts, packages/codegen-ui/lib/generate-view-definition/helpers/order-filter-columns.ts, packages/codegen-ui/lib/types/view/defaults.ts, packages/codegen-ui/lib/types/view/table-definition.ts, packages/codegen-ui/lib/types/view/table.ts, packages/codegen-ui/lib/types/view/view.ts
* Table definition to be used by table renderer
* Some types are fixed to use primitive instead of instanced 
=> feat: table definition for renderer

package-lock.json, packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/amplify-ui-renderers/form.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui/example-schemas/forms/post-datastore-update.json, packages/test-generator/integration-test-templates/cypress/e2e/generate-spec.cy.ts, packages/test-generator/lib/forms/form-custom-create.json, packages/test-generator/lib/forms/form-custom-update.json, packages/test-generator/lib/forms/form-update.json, packages/test-generator/lib/forms/index.ts
- Adds datastore update action
=> chore: adds update datastore action for forms

package-lock.json, packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/amplify-ui-renderers/form.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui/example-schemas/forms/post-datastore-update.json, packages/codegen-ui/lib/__tests__/generate-form-definition/generate-form-definition.test.ts, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/form-field.test.ts, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/map-elements.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/field-type-map.ts, packages/codegen-ui/lib/generate-form-definition/helpers/form-field.ts, packages/codegen-ui/lib/generate-view-definition/generate-table-definition.ts, packages/codegen-ui/lib/types/form/form-definition-element.ts, packages/codegen-ui/lib/types/form/index.ts, packages/test-generator/integration-test-templates/cypress/e2e/generate-spec.cy.ts, packages/test-generator/lib/forms/form-custom-create.json, packages/test-generator/lib/forms/form-custom-update.json, packages/test-generator/lib/forms/form-update.json, packages/test-generator/lib/forms/index.ts
=> Tagged release/forms and views

packages/codegen-ui/lib/__tests__/generate-view-definition/generate-table-definition.test.ts, packages/codegen-ui/lib/types/view/defaults.ts, packages/codegen-ui/lib/types/view/table-definition.ts, packages/codegen-ui/lib/types/view/view.ts
* narrow down view configuration type
* added enableOnRowClick prop in table config
=> fix: fix to narrow view config type

packages/codegen-ui-react/lib/amplify-ui-renderers/amplify-view-renderer.ts, packages/codegen-ui-react/lib/views/react-view-renderer.ts, packages/codegen-ui/index.ts, packages/codegen-ui/lib/__tests__/generate-view-definition/generate-table-definition.test.ts, packages/codegen-ui/lib/generate-view-definition/generate-table-definition.ts, packages/codegen-ui/lib/generate-view-definition/index.ts, packages/codegen-ui/lib/types/view/view-metadata.ts
Initial commit so we can build from this
=> feat: initial commit for view (table) renderer

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-views.test.ts.snap, packages/codegen-ui-react/lib/__tests__/__utils__/amplify-renderer-generator.ts, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-views.test.ts, packages/codegen-ui-react/lib/amplify-ui-renderers/amplify-view-renderer.ts, packages/codegen-ui-react/lib/index.ts, packages/codegen-ui-react/lib/react-table-renderer.ts, packages/codegen-ui-react/lib/views/react-view-renderer.ts, packages/codegen-ui/example-schemas/datastore/person.json, packages/codegen-ui/example-schemas/views/datastore-table-no-header.json, packages/codegen-ui/example-schemas/views/datastore-table.json
=> feat: table renderer

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/views/react-view-renderer.ts, packages/codegen-ui/lib/validation-helper.ts
=> feat: view renderer with variable statements and base types

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-views.test.ts.snap, packages/codegen-ui-react/lib/react-table-renderer-helper.ts, packages/codegen-ui-react/lib/react-table-renderer.ts, packages/codegen-ui/example-schemas/views/datastore-table.json, packages/codegen-ui/lib/types/string-format.ts, packages/codegen-ui/lib/types/view/view-metadata.ts
* using formatter in codegenned table jsx
=> fix: codegenning formatter in table jsx

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-views.test.ts.snap, packages/codegen-ui-react/lib/react-table-renderer.ts
* formatter call is now conditionally rendered
=> fix: conditionally codegenning formatter call

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-views.test.ts.snap, packages/codegen-ui-react/lib/react-table-renderer-helper.ts, packages/codegen-ui-react/lib/react-table-renderer.ts, packages/codegen-ui/example-schemas/views/post-table-custom-format.json, packages/codegen-ui/example-schemas/views/post-table-datastore.json, packages/codegen-ui/example-schemas/views/table-from-custom-json.json, packages/codegen-ui/example-schemas/views/table-from-datastore-no-header.json, packages/codegen-ui/example-schemas/views/table-from-datastore.json, packages/codegen-ui/lib/__tests__/generate-view-definition/generate-table-definition.test.ts, packages/codegen-ui/lib/__tests__/string-formatter.test.ts, packages/codegen-ui/lib/generate-view-definition/generate-table-definition.ts, packages/codegen-ui/lib/types/string-format.ts, packages/codegen-ui/lib/types/view/defaults.ts, packages/codegen-ui/lib/types/view/view.ts, packages/codegen-ui/lib/utils/string-formatter.ts
* Matching types with model for cleaner mapping from both in UI Builder and CLI to codegen
* FIx codegenned argument shape for formatter for cleaner ast code
=> fix: Fix type mismatch with model types

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui/example-schemas/forms/custom-with-sectional-elements.json, packages/codegen-ui/lib/__tests__/utils/form-component-metadata.test.ts, packages/codegen-ui/lib/utils/form-component-metadata.ts, packages/codegen-ui/lib/utils/form-to-component/map-form-definition-to-component.ts
- Don't map mutation hooks for sectional elements
- confirm rendering w/ tests
=> chore: refine rendering of form sectional elements

packages/codegen-ui/lib/types/form/sectional-element.ts
Making position optional on sectional elements makes updating easier without breaking functionality.
=> chore: update form sectional element type

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui/example-schemas/forms/post-custom-create.json, packages/codegen-ui/example-schemas/forms/post-datastore-create.json, packages/codegen-ui/example-schemas/forms/post-datastore-update.json, packages/codegen-ui/lib/validation-helper.ts
* Validation on entity names to follow valid React component names
=> fix: entity name validation

packages/codegen-ui/lib/generate-form-definition/helpers/map-cta.ts
=> fix: add optional chaining for cta config and nullish coalese

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/utils/__snapshots__/string-formatter.test.ts.snap, packages/codegen-ui-react/lib/amplify-ui-renderers/form.ts, packages/codegen-ui-react/lib/utils/string-formatter.ts
=> fix: date format and form onSubmitBefore

.github/workflows/release.yml, packages/codegen-ui-react/lib/react-studio-template-renderer-helper.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui-react/package.json
=> chore: Merge fixes to tagged branch

packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/model-fields-configs.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/field-type-map.ts, packages/codegen-ui/lib/generate-form-definition/helpers/form-field.ts, packages/codegen-ui/lib/generate-form-definition/helpers/model-fields-configs.ts, packages/codegen-ui/lib/types/form/form-definition-element.ts, packages/codegen-ui/lib/types/form/form-definition.ts, packages/codegen-ui/lib/types/form/form-metadata.ts, packages/codegen-ui/lib/types/form/index.ts, packages/codegen-ui/lib/utils/form-component-metadata.ts
- Adds configuration for Array type input fields
Next PR:
- ArrayField component
=> Form arrays

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/event-targets.ts, packages/codegen-ui/example-schemas/datastore/input-gallery.json, packages/codegen-ui/example-schemas/forms/input-gallery-create.json, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/form-field.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/defaults.ts, packages/codegen-ui/lib/generate-form-definition/helpers/form-field.ts, packages/codegen-ui/lib/types/form/form-definition-element.ts
Handle RadioGroupField of Boolean type by setting options to 'true' and 'false' w/ customizable display value.
=> chore: handle RadioGroupField of Boolean type

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui/lib/__tests__/__utils__/basic-form-definition.ts, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/form-field.test.ts, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/map-elements.test.ts, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/model-fields-configs.test.ts, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/position.test.ts, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/sectional-element.test.ts, packages/codegen-ui/lib/__tests__/utils/form-component-metadata.test.ts, packages/codegen-ui/lib/generate-form-definition/generate-form-definition.ts, packages/codegen-ui/lib/generate-form-definition/helpers/defaults.ts, packages/codegen-ui/lib/generate-form-definition/helpers/map-styles.ts, packages/codegen-ui/lib/generate-form-definition/helpers/model-fields-configs.ts, packages/codegen-ui/lib/types/form/form-definition.ts, packages/codegen-ui/lib/types/form/style.ts, packages/codegen-ui/lib/utils/form-to-component/map-form-definition-to-component.ts
- remove alignment
- require layout values from form definition
- add padding
- auto-exclude relationship fields
- change auto-mapped default value
=> chore: clean up form auto gen

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts
- makes override field keys optional in types file
=> fix: make override keys optional

packages/codegen-ui/lib/generate-view-definition/generate-table-definition.ts
=> fix: fetch table config with nullish operator

packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json
=> chore: use ts versions below 4.5

packages/codegen-ui-react/lib/react-utils-studio-template-renderer.ts, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/position.test.ts
get rid of duplicate declarations. CLI will need update as well.
Additional changes - chunk up position tests better per Albert's comment on this PR: https://github.com/aws-amplify/amplify-codegen-ui/pull/619
=> fix: change util file rendering

package-lock.json, packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui/lib/__tests__/utils/form-to-component/map-form-definition-to-component.test.ts, packages/codegen-ui/lib/utils/form-to-component/map-form-definition-to-component.ts
=> chore: remove unnecessary grids

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/test-generator/integration-test-templates/cypress/e2e/form-spec.cy.ts
- Validate on blur
- Don't validate onChange unless there is error
=> chore: validate onBlur and only conditionally onChange

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/amplify-ui-renderers/amplify-form-renderer.ts, packages/codegen-ui/lib/__tests__/utils/form-to-component/map-form-definition-to-component.test.ts, packages/codegen-ui/lib/utils/form-to-component/map-form-definition-to-component.ts
Problem: padding is not being correctly applied to forms. It is being applied as the outer padding of just the form input elements, excluding the CTA.
Solution: refactor form layout so that the top-level component is the Grid that contains all form input elements as well as the CTA. Verified that all form functionalities work through the `as="form"` prop.
=> fix: add padding properly to forms

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui/lib/utils/form-to-component/helpers/map-cta-buttons.ts
Confirmed that the form now looks right.
=> chore: remove top margin from CTA row

commitlint.config.js
Increase to max header for commits so that we don't break stylelint
=> fix: increase commit max length

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui/example-schemas/forms/post-datastore-create-row.json, packages/codegen-ui/lib/utils/form-to-component/map-form-definition-to-component.ts
=> fix: forms row layout

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/amplify-ui-renderers/form.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui-react/lib/forms/form-state.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/react-component-render-helper.ts, packages/codegen-ui-react/lib/utils/forms/layout-helpers.ts, packages/codegen-ui/example-schemas/forms/bio-nested-create.json, packages/codegen-ui/lib/types/form/form-metadata.ts, packages/codegen-ui/lib/utils/form-component-metadata.ts, packages/codegen-ui/lib/utils/form-to-component/map-form-definition-to-component.ts
When using design tokens in forms, we were not properly mapping them. This PR fixes that so they we include the required hooks and render out rhe property accessors.
=> feat: take design tokens into consideration when rendering

packages/codegen-ui/lib/__tests__/utils/breakpoint-utils.test.ts, packages/codegen-ui/lib/utils/breakpoint-utils.ts
- only create breakpoint hook with valid breakpoint sizes
=> fix: remove invalid breakpoints

CHANGELOG.md, lerna.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.4.1

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/utils/forms/array-field-component.ts, packages/codegen-ui/example-schemas/forms/custom-with-array-field.json, packages/codegen-ui/example-schemas/forms/post-datastore-create-with-custom-array.json, packages/codegen-ui/lib/__tests__/generate-form-definition/generate-form-definition.test.ts, packages/codegen-ui/lib/__tests__/utils/form-component-metadata.test.ts, packages/codegen-ui/lib/generate-form-definition/helpers/form-field.ts, packages/codegen-ui/lib/types/form/form-definition-element.ts, packages/codegen-ui/lib/utils/form-component-metadata.ts
Studio model now has an isArray property for form fields which isn't being handled when generating form definitions
Update type and helper methods to include support for isArray.
=> feat: add handling for isArray in form field model

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/utils/forms/array-field-component.ts
Have the input field for ArrayField auto-focus when switching to editing mode.
=> fix: fix ArrayField focus

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/event-targets.ts
https://app.asana.com/0/1202966106210868/1203050023493661/f
Fix js error `NaN is not a function`
=> fix: nan is not a function

packages/codegen-ui/index.ts, packages/codegen-ui/lib/__tests__/check-support.test.ts, packages/codegen-ui/lib/check-support.ts
This helper will be used in UI and CLI to determine what models to autogen forms for.
=> chore: add checker for models supported as forms

packages/codegen-ui/lib/__tests__/utils/breakpoint-utils.test.ts, packages/codegen-ui/lib/utils/breakpoint-utils.ts
ref pr661 merged back into feature branch
=> fix: remove invalid breakpoints (#661)

.github/workflows/release.yml
- Move commit message into env variable
=> fix: move commit message into env variable

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-state.ts, packages/codegen-ui/example-schemas/datastore/post.json
This PR stringifies JSON on load so that it doesn't show as `[object Object]`
=> fix: stringify awsjson

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-state.ts, packages/codegen-ui-react/lib/imports/import-collection.ts
- Fix ArrayField component when DS array type record value is null
=> fix: arrayfield items prop fallback to empty array when record is null

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui/example-schemas/forms/post-custom-update.json
=> fix: parse json on save

CHANGELOG.md, lerna.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.4.2

CHANGELOG.md, lerna.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.5.0

CHANGELOG.md, lerna.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.5.1

package.json, packages/codegen-ui-golden-files/lib/react/forms/datastore-create-form-with-has-one-relationship/BookCreateForm.d.ts, packages/codegen-ui-golden-files/lib/react/forms/datastore-create-form-with-has-one-relationship/BookCreateForm.jsx, packages/codegen-ui-golden-files/lib/react/forms/datastore-create-form-with-has-one-relationship/schema.ts
=> chore: add golden for create form with hasOne relationship

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.5.2

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-views.test.ts.snap, packages/codegen-ui-react/lib/__tests__/__utils__/amplify-renderer-generator.ts, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-views.test.ts, packages/codegen-ui-react/lib/amplify-ui-renderers/amplify-view-renderer.ts, packages/codegen-ui-react/lib/index.ts, packages/codegen-ui-react/lib/react-expander-renderer.ts, packages/codegen-ui-react/lib/react-table-renderer-helper.ts, packages/codegen-ui-react/lib/views/react-view-renderer.ts, packages/codegen-ui/example-schemas/views/expander-with-binding-prop.json, packages/codegen-ui/example-schemas/views/expander-with-component-slot.json, packages/codegen-ui/lib/__tests__/validation-helper.test.ts, packages/codegen-ui/lib/generate-view-definition/generate-table-definition.ts, packages/codegen-ui/lib/types/view/collection.ts, packages/codegen-ui/lib/types/view/view.ts, packages/test-generator/integration-test-templates/cypress/e2e/generate-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/views-spec.cy.ts, packages/test-generator/integration-test-templates/src/App.tsx, packages/test-generator/integration-test-templates/src/ViewTests.tsx, packages/test-generator/lib/generators/BrowserTestGenerator.ts, packages/test-generator/lib/generators/NodeTestGenerator.ts, packages/test-generator/lib/generators/TestGenerator.ts, packages/test-generator/lib/views/index.ts, packages/test-generator/lib/views/listing-expander-with-component-slot.json
Adds a new expander renderer under view renderer
=> feat: expander init

.github/workflows/check.yml, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/map-elements.test.ts, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/sectional-element.test.ts, packages/codegen-ui/lib/generate-form-definition/generate-form-definition.ts, packages/codegen-ui/lib/generate-form-definition/helpers/sectional-element.ts, packages/codegen-ui/lib/types/form/index.ts, packages/codegen-ui/lib/types/form/sectional-element.ts
- Updated type and helper methods to support excluded sectional elements similar to excluded fields.
=> feat: add handling for excluded sectional elements

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/imports/import-collection.test.ts, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/amplify-ui-renderers/form.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/forms/type-helper.ts, packages/codegen-ui-react/lib/imports/import-collection.ts, packages/codegen-ui/example-schemas/datastore/flex.json, packages/codegen-ui/example-schemas/forms/flex-datastore-create.json, packages/codegen-ui/example-schemas/forms/flex-datastore-update.json, packages/codegen-ui/lib/utils/index.ts
- fix model name colliding for forms
=> chore: alias model name collision for forms

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts, packages/codegen-ui-react/lib/forms/form-state.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/utils/forms/array-field-component.ts, packages/codegen-ui/example-schemas/forms/bio-nested-create.json, packages/test-generator/integration-test-templates/cypress/e2e/form-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/generate-spec.cy.ts, packages/test-generator/integration-test-templates/src/FormTests.tsx, packages/test-generator/lib/forms/custom-form-nested-json-create.json, packages/test-generator/lib/forms/index.ts
Change rendering logic so that nested arrays are supported. Add E2E test
=> fix: support nested arrays

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.5.3

packages/codegen-ui-react/lib/__tests__/__snapshots__/react-theme-studio-template-renderer.test.ts.snap, packages/codegen-ui-react/lib/__tests__/react-theme-studio-template-renderer.test.ts, packages/codegen-ui-react/lib/imports/import-mapping.ts, packages/codegen-ui-react/lib/react-theme-studio-template-renderer.ts
https://app.asana.com/0/1202185248783861/1203287913178604/f
Add an option to render the default theme instead.
=> feat: render default theme option

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.5.4

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-state.ts, packages/codegen-ui/example-schemas/datastore/input-gallery.json
- Remove stringifying initial value for json type that isArray
=> fix: remove stringify for json type array initial value

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap
Two PR's merged out of order and now publish is failing
=> fix: update snapshot

packages/test-generator/e2e-test-templates/src/App.js
=> fix: accommodate major release of aws-amplify in CLI test

packages/codegen-ui-golden-files/lib/react/forms/datastore-create-form-with-many-to-many-relationship/TagCreateForm.d.ts, packages/codegen-ui-golden-files/lib/react/forms/datastore-create-form-with-many-to-many-relationship/TagCreateForm.jsx, packages/codegen-ui-golden-files/lib/react/forms/datastore-create-form-with-many-to-many-relationship/schema.ts
Adding tag create form with many-to-many relationship. Tested this out locally with an amplify-connected app.
=> feat: adding many-to-many relationship create form golden file

packages/codegen-ui-react/lib/react-required-dependency-provider.ts
=> fix: fix typo in required dependency provider

packages/codegen-ui-golden-files/lib/react/forms/datastore-create-form-with-many-to-many-relationship/TagUpdateForm.d.ts, packages/codegen-ui-golden-files/lib/react/forms/datastore-create-form-with-many-to-many-relationship/TagUpdateForm.jsx
Add tag update golden file with manyToMany relationship. Test it in a local app ✅
=> Add tag update golden file with manyToMany relationship

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/amplify-ui-renderers/form.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper.ts
This reverts commit 7ab3126a0c9ef9e38fc4295dbb56e628c0dcdeb5.
=> Revert "fix: refresh stale data on update form"

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.5.5

packages/codegen-ui-golden-files/lib/react/forms/datastore-update-form-with-has-one-relationship/BookUpdateForm.d.ts, packages/codegen-ui-golden-files/lib/react/forms/datastore-update-form-with-has-one-relationship/BookUpdateForm.jsx, packages/codegen-ui-golden-files/lib/react/forms/datastore-update-form-with-has-one-relationship/schema.ts
Adds golden file for an Update form that uses a hasOne relationship
Link to previous PR that I was unable to pull over due to merge conflicts: https://github.com/aws-amplify/amplify-codegen-ui/pull/752
=> chore: add golden file for update form with hasOne relationship

packages/test-generator/integration-test-templates/cypress/e2e/form-spec.cy.ts, packages/test-generator/integration-test-templates/src/FormTests.tsx, packages/test-generator/integration-test-templates/src/models/index.d.ts, packages/test-generator/integration-test-templates/src/models/schema.js, packages/test-generator/lib/forms/datastore-form-create-all-supported-form-fields.json, packages/test-generator/lib/models/schema.ts
- Add integ test for HAS_ONE relationship
- Update syntax for the CustomCreateDog test
=> chore: add integ test for hasOne relationship

packages/test-generator/integration-test-templates/src/models/index.d.ts, packages/test-generator/integration-test-templates/src/models/index.js, packages/test-generator/integration-test-templates/src/models/schema.js, packages/test-generator/lib/forms/datastore-form-create-all-supported-form-fields.json, packages/test-generator/lib/forms/datastore-form-update-all-supported-form-fields.json, packages/test-generator/lib/models/schema.ts
Update schema for relationship test(`belongsTo`, `hasMany` and `manyToMany`)
=> chore: update schema for relationship tests

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/display-value.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/map-from-fieldConfigs.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/render-array-field.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/render-checkers.ts, packages/codegen-ui/example-schemas/datastore/tag-post.json, packages/codegen-ui/lib/utils/form-component-metadata.ts, packages/codegen-ui/package-lock.json
https://app.asana.com/0/1202185248783861/1203326184542750/f
Add support for enum arrays to show badge text display text instead of the records value. 
=> fix: support display value for array of enums

packages/codegen-ui-react/lib/__tests__/__snapshots__/react-studio-template-renderer-helper.test.ts.snap, packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/type-helper.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/primitive.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts
- Adds types for component overrides
- Changes primitive override helper type to be more generic
=> chore: add types for component overrides

packages/codegen-ui-golden-files/lib/react/forms/datastore-create-form-with-has-many-relationship/SchoolCreateForm.d.ts, packages/codegen-ui-golden-files/lib/react/forms/datastore-create-form-with-has-many-relationship/SchoolCreateForm.jsx, packages/codegen-ui-golden-files/lib/react/forms/datastore-create-form-with-has-many-relationship/schema.ts, packages/codegen-ui-golden-files/lib/react/forms/datastore-update-form-with-has-many-relationship/SchoolUpdateForm.d.ts, packages/codegen-ui-golden-files/lib/react/forms/datastore-update-form-with-has-many-relationship/SchoolUpdateForm.jsx, packages/codegen-ui-golden-files/lib/react/forms/datastore-update-form-with-has-many-relationship/schema.ts
Add hasMany golden files for create and update form
=> chore: add hasMany golden files for create and update form

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/test-generator/integration-test-templates/src/models/index.d.ts
Update to use lazy loading types for integ tests
=> chore: update lazy loading types for integ tests

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
includes fix for nested boolean values in forms and runtime type safety for `in` operator
=> chore(release): v2.5.6

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/render-array-field.ts, packages/codegen-ui-react/lib/utils/forms/array-field-component.ts, packages/test-generator/integration-test-templates/cypress/e2e/update-form-spec.cy.ts
=> fix: fix label and edit behavior of hasOne relationship field

packages/test-generator/integration-test-templates/cypress/e2e/create-form-spec.cy.ts, packages/test-generator/integration-test-templates/src/CreateFormTests.tsx
Add integ test for `manyToMany` relationship create form
=> test: add integ test for create manyToMany relationship

packages/test-generator/integration-test-templates/cypress/e2e/update-form-spec.cy.ts, packages/test-generator/integration-test-templates/src/UpdateFormTests.tsx, packages/test-generator/lib/forms/datastore-form-update-all-supported-form-fields.json
This PR adds a belongsTo relationship field to update form integ test
=> Add integration test for belongsTo update form

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/form-state.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/model-fields.ts, packages/codegen-ui/example-schemas/datastore/post.json, packages/codegen-ui/lib/__tests__/generate-form-definition/helpers/model-fields-configs.test.ts, packages/codegen-ui/lib/check-support.ts, packages/codegen-ui/lib/generate-form-definition/helpers/form-field.ts, packages/codegen-ui/lib/generate-form-definition/helpers/model-fields-configs.ts, packages/test-generator/integration-test-templates/cypress/e2e/create-form-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/utils/form.ts, packages/test-generator/integration-test-templates/src/UpdateFormTests.tsx, packages/test-generator/integration-test-templates/src/models/index.d.ts, packages/test-generator/integration-test-templates/src/models/schema.js, packages/test-generator/lib/forms/datastore-form-create-all-supported-form-fields.json, packages/test-generator/lib/models/schema.ts
- allow nonModel fields as TextAreaField like JSON 
=> chore: allow non model fields

packages/codegen-ui/lib/__tests__/__utils__/mock-schemas.ts, packages/codegen-ui/lib/__tests__/generic-from-datastore.test.ts, packages/codegen-ui/lib/generic-from-datastore.ts, packages/codegen-ui/lib/types/data.ts
Prep for cpk support by adding primary keys to the generic data schema
=> chore: add primary keys to generic data schema

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/amplify-ui-renderers/form.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/cta-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui/example-schemas/datastore/cpk-relationships.json, packages/codegen-ui/example-schemas/forms/cpk-teacher-datastore-update.json, packages/codegen-ui/lib/__tests__/check-support.test.ts, packages/codegen-ui/lib/__tests__/generate-view-definition/generate-table-definition.test.ts, packages/codegen-ui/lib/utils/component-metadata.ts
Support cpk for forms with manyToMany relationships. Integ test will be added in separate PR
- Fix type errors in tests
- Rename model & form used in snapshot test
- move `dataSchemaMetadata` under `componentMetadata`
=> feat: support cpk for manyToMany form

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/cta-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts, packages/codegen-ui/example-schemas/datastore/cpk-relationships.json
Support CPK for forms with hasMany relationship. Integ test coming in separate PR.
=> feat: support cpk for forms with hasMany relationship

.github/workflows/codeql.yml
Replaces the deprecated LGTM bot with Github Code Coverage metrics.
=> chore: add codeql config file

packages/test-generator/integration-test-templates/cypress/e2e/generate-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/update-form-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/utils/form.ts, packages/test-generator/integration-test-templates/src/UpdateFormTests.tsx, packages/test-generator/integration-test-templates/src/models/index.d.ts, packages/test-generator/integration-test-templates/src/models/index.js, packages/test-generator/integration-test-templates/src/models/schema.js, packages/test-generator/lib/forms/datastore-form-update-cpk-teacher.json, packages/test-generator/lib/forms/index.ts, packages/test-generator/lib/models/schema.ts
=> test: add integ test for cpk support

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/display-value.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/form-state.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/index.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/utils/forms/array-field-component.ts
Selected options should not be available in the dropdown list. This PR will address the issue
- Filter out selected options on Autocomplete
- Fix a conditional bug
=> chore: filter out selected options on Autocomplete

packages/codegen-ui-react/lib/react-studio-template-renderer.ts
- return importCollection in renderComponentOnly
=> chore: return importCollection in renderComponentOnly

.github/workflows/canaries.yml, .github/workflows/check.yml, packages/test-generator/e2e-test-templates/cypress/e2e/e2e-tests.cy.js, packages/test-generator/e2e-test-templates/src/App.js
So that we can stop having to rotate API Key
=> test: update cli test to use cognito user

packages/test-generator/e2e-test-templates/src/App.js
Needed to do this to auth with cognito user
=> fix: set authModeStrategyType in e2e test

CHANGELOG.md, lerna.json, package-lock.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.7.0

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/event-handler-props.ts, packages/test-generator/integration-test-templates/src/UpdateFormTests.tsx, packages/test-generator/integration-test-templates/src/models/index.d.ts, packages/test-generator/integration-test-templates/src/models/schema.js, packages/test-generator/lib/forms/datastore-form-create-all-supported-form-fields.json, packages/test-generator/lib/forms/datastore-form-update-all-supported-form-fields.json, packages/test-generator/lib/models/schema.ts
Incorrect validation logic was blocking users from adding required relationship fields. This changes it and adds integ test.
The validation logic for relationships most likely needs more refinement. But this will at least unblock essential functionality.
The form schemas in e2e tests had some wrong keys that were not impacting functionality.
=> fix: fix validation for required relationships

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.7.1

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.7.2

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/react-component-renderer.ts, packages/codegen-ui-react/lib/utils/forms/array-field-component.ts
The hard-coded token interferes with theming, as pointed out by CMSv2 team. 
Confirmed with dev who implemented the token that it is not necessary.
=> chore: remove token on ArrayField link button

.circleci/publish.sh
N/A 
Added --no-verify-access flag for lerna publish command for using automated token
=> fix: Lerna Publish changes

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/__tests__/__utils__/mock-data-schemas.ts, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react.test.ts, packages/codegen-ui-react/lib/amplify-ui-renderers/collection.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui/example-schemas/compositePersonCollectionComponent.json, packages/test-generator/integration-test-templates/cypress/e2e/generate-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/generated-components-spec.cy.ts, packages/test-generator/integration-test-templates/src/ComponentTests.tsx, packages/test-generator/lib/components/collections/collectionWithCompositeKeysAndRelationships.json, packages/test-generator/lib/components/collections/index.ts, packages/test-generator/lib/components/property-binding/componentBoundToCompositeDog.json, packages/test-generator/lib/components/property-binding/index.ts, packages/test-generator/lib/generators/NodeTestGenerator.ts
- Map keys of items dynamically based on model
- Add integ tests for relationship loading in collections
=> chore: support CPK for collections

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.8.0

packages/test-generator/integration-test-templates/cypress/e2e/workflow-spec.cy.ts, packages/test-generator/integration-test-templates/src/ComponentTests.tsx, packages/test-generator/integration-test-templates/src/UpdateFormTests.tsx, packages/test-generator/integration-test-templates/src/WorkflowTests.tsx, packages/test-generator/integration-test-templates/src/models/index.d.ts, packages/test-generator/integration-test-templates/src/models/index.js, packages/test-generator/integration-test-templates/src/models/schema.js, packages/test-generator/lib/models/schema.graphql, packages/test-generator/lib/models/schema.ts
1. Add `schema.graphl` representing the E2E test schema so that we can easily update the generated model files from it.
2. Update all model files to one associated with `codegenVersion` 3.3.5.
3. Address any type issues
Additional change: Fix 1 redundancy in workflow test.
=> test: update codegenVersion to 3.3.5

packages/codegen-ui-react/lib/__tests__/forms/validation.test.ts
Refactor date validation test cases with proper test case iteration
=> chore: refactor date validation test cases

packages/test-generator/integration-test-templates/cypress/e2e/form/DSAllSupportedFormFields-spec.cy.ts, packages/test-generator/integration-test-templates/src/FormTests/DSAllSupportedFormFields.tsx
For the Update AllSupportedFormFields form in the cypress tests, adds value update tests for all fields.
=> chore: add update tests for AllSupportedFormFields

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/all-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/event-handler-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/model-values.ts, packages/codegen-ui-react/lib/react-component-render-helper.ts, packages/codegen-ui/example-schemas/forms/custom-with-array-field.json, packages/codegen-ui/example-schemas/forms/flex-datastore-update.json, packages/codegen-ui/lib/types/form/index.ts, packages/codegen-ui/lib/utils/form-component-metadata.ts, packages/test-generator/integration-test-templates/cypress/e2e/form/CustomDog-spec.cy.ts, packages/test-generator/integration-test-templates/src/FormTests/CustomDog.tsx, packages/test-generator/lib/forms/custom-form-create-dog.json
- add fixed valueMappings to Autocomplete field
=> chore: add fixed valueMappings for Autocomplete field

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.9.0

packages/test-generator/integration-test-templates/cypress/e2e/form/BidirectionalOwner-Dog-spec.cy.ts, packages/test-generator/integration-test-templates/src/FormTests/DSBidirectionalOwnerDog.tsx
we need a bi directional has many integ test
add the removal error test
=> chore: bidirectional has many test

packages/test-generator/integration-test-templates/cypress/e2e/form/BidirectionalToy-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/generate-spec.cy.ts, packages/test-generator/integration-test-templates/src/FormTests/DSBidirectionalToy.tsx, packages/test-generator/integration-test-templates/src/FormTests/index.tsx, packages/test-generator/lib/forms/datastore-form-create-bidirectional-dog.json, packages/test-generator/lib/forms/index.ts
We needed a test to test updating a belongs to relationship.
Create a test to:
1. create dog1, create Toy1 with Dog1 (since dog is required on Toy)
2. In create Dog2 form, connect Toy1 to Dog2
3. Check if Toy1 is connected to Dog2 after creating Dog2
=> chore: add bi directional test

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/form-state.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/value-props.ts, packages/codegen-ui/example-schemas/forms/nested-json-create.json, packages/codegen-ui/example-schemas/forms/nested-json-update.json, packages/test-generator/integration-test-templates/cypress/e2e/form/CustomNestedJSON-spec.cy.ts
Custom JSON forms nested text field arrays could not update. Because the TextField was going from uncontrolled to controlled and would not update beyond their initial value. 
Broken generated code
```
const initialValues = {
basics: {},
// This is the nested object with the Text
favoriteThings: {},
active: false,
enabled: false,
};
const [favoriteThings, setFavoriteThings] = React.useState(
initialValues.favoriteThings
);
<ArrayField ...>
<TextField
label="Animals"
value={favoriteThings["animals"]} <--- this value is undefined
```
Fixed generated code
```
<TextField
label="Animals"
value={currentFavoriteThingsAnimalsValue} <--- uses the currentArrayFieldValue instead
```
Pressing the clear button would throw an error for a function that was not defined.
Use the current array value of the …
=> fix: nested json array uncontrolled to controlled component fix

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
These are automated changes from the command in our release process. https://github.com/aws-amplify/amplify-codegen-ui/blob/main/CONTRIBUTING.md#publish-a-release
2.10.0 release includes custom form nested list bug fix.
=> chore(release): v2.10.0

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
new bugfix needs to be released
perform release workflow
=> chore(release): v2.11.1

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.12.0

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.12.1

packages/codegen-ui-react/lib/react-required-dependency-provider.ts, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/test-generator/package-lock.json, packages/test-generator/package.json
There were recent changes for `StorageManager`.
Bump `ui-react` and `ui-react-storage` to latest versions.
=> chore: bump ui-react and ui-react-storage

CHANGELOG.md, lerna.json, package-lock.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.12.2

packages/codegen-ui-react/lib/forms/form-renderer-helper/render-checkers.ts
Per comment on previous PR - https://github.com/aws-amplify/amplify-codegen-ui/pull/870#discussion_r1061839285,
improve safety of type coercion.
=> chore: improve safety of coercion

packages/test-generator/integration-test-templates/cypress/e2e/form/BidirectionalDog-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/form/BidirectionalOwner-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/form/BidirectionalToy-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/form/CustomDog-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/form/CustomNestedJSON-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/form/DSAllSupportedFormFields-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/form/DSCPKTeacher-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/form/DSCar-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/form/DSCompositeDog-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/form/DSCompositeToy-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/form/DSDealership-spec.cy.ts, packages/test-generator/integration-test-templates/cypress/e2e/form/ModelWithVariableCollisions-spec.cy.ts, packages/test-generator/lib/models/schema.graphql
E2E test descriptions for form builder does not give much information on what functionality is being tested.
As discussed in dev sync, we need a systematic way of linking tests to features, but for now, here are:
1. comments on the schema.graphql file
2. more descriptive test descriptions
=> chore: update test descriptions

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.13.0

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.13.1

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.14.0

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.14.1

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.14.2

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/cta-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts, packages/codegen-ui/example-schemas/datastore/school-student-collision.json
Model name colliding with field name in hasMany relationship
Alias colliding model name
=> fix: alias colliding imported model name in hasMany relationship

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts
Wrapping the graphql query result so it awaits the result before attempting to access the data
=> fix: wrapping list graphql result for await

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/all-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/bidirectional-relationship.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/cta-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/event-handler-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/form-state.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/model-values.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts, packages/codegen-ui-react/lib/react-component-renderer.ts, packages/codegen-ui-react/lib/react-studio-template-renderer.ts, packages/codegen-ui-react/lib/utils/graphql.ts, packages/codegen-ui-react/lib/workflow/action.ts, packages/codegen-ui/example-schemas/datastore/car.json, packages/codegen-ui/example-schemas/datastore/relationships/has-many-autocomplete-post.json, packages/codegen-ui/example-schemas/forms/relationships/update-post.json, packages/codegen-ui/lib/utils/form-component-metadata.ts
To support graphql in relationship forms with autocomplete fields
Note diff in snapshot for new and existing forms.
=> feat: add graphql support for relationship forms with autocomplete field

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
releasing graphql support
ran release process from the contributing doc
GitHub issue:
=> chore(release): v2.14.3

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react.test.ts.snap, packages/codegen-ui-react/lib/utils/graphql.ts
input obj in graphql query
remove input in graphql queries
=> fix: remove input obj in graphql query

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
new release is needed for use in production services
releasing new minor rev to signify the readiness of codegen capability
GitHub issue:
=> chore(release): v2.15.0

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.15.1

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.15.2

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
Bug fixes need to be released.
Initiate a patch release containing the bug fixes.
GitHub issue:
=> chore(release): v2.15.3

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.15.4

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.15.5

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
bugfixes need to be published
create new patch release
GitHub issue:
=> chore(release): v2.15.6

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
bugfixes need to be released
create new patch release
GitHub issue:
=> chore(release): v2.15.7

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
bug fixes require release
create new patch release
GitHub issue:
=> chore(release): v2.15.8

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.15.9

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/__tests__/studio-ui-codegen-react-forms.test.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts
We needed more unit test coverage of amplify js v6 api updates.
Added custom primary key and many to many model tests. It found one bug and the fix is part of the commit to get the tests passing.
GitHub issue:
=> fix: added more amplify js v6 unit tests fixed a bug

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
A release for codegen amplify js v6 rendering support
Ran the release steps in the contributing guide
GitHub issue:
=> chore(release): v2.17.0

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.18.0

packages/codegen-ui-react/package.json
move aws-amplify to dependencies
=> fix: move aws-amplify to deps

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.19.0

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.19.1

packages/codegen-ui-react/lib/react-utils-studio-template-renderer.ts
change utils file extension to js to prevent duplicate utils files in apps\
=> fix: change utils file to js

packages/codegen-ui-react/lib/__tests__/utils/__snapshots__/render-util-functions.test.ts.snap, packages/codegen-ui-react/lib/__tests__/utils/render-util-functions.test.ts, packages/codegen-ui-react/lib/imports/import-mapping.ts, packages/codegen-ui-react/lib/react-utils-studio-template-renderer.ts, packages/codegen-ui-react/lib/utils-file-functions/hooks/useAuthSignoutAction.ts
imports changed for aws-amplify v6
=> update imports for aws-amplify v6

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.19.2

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.19.3

packages/codegen-ui-react/lib/__tests__/__snapshots__/studio-ui-codegen-react-forms.test.ts.snap, packages/codegen-ui-react/lib/forms/form-renderer-helper/event-handler-props.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/form-state.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/model-values.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/relationship.ts, packages/codegen-ui-react/lib/forms/form-renderer-helper/render-array-field.ts, packages/codegen-ui-react/lib/forms/react-form-renderer.ts
Merges in a commit from a patch branch
This one: https://github.com/aws-amplify/amplify-codegen-ui/pull/1130
merges in a previously approved commit
none
GitHub issue:
=> fix: undefined reference errors in ToLinkMap callback

CHANGELOG.md, lerna.json, packages/codegen-ui-golden-files/CHANGELOG.md, packages/codegen-ui-golden-files/package-lock.json, packages/codegen-ui-golden-files/package.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
release latest patches.
commits are auto-created using `npm run version` command
GitHub issue:
=> chore(release): v2.19.4

CHANGELOG.md, lerna.json, packages/codegen-ui-react/CHANGELOG.md, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/CHANGELOG.md, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/CHANGELOG.md, packages/test-generator/package-lock.json, packages/test-generator/package.json
=> chore(release): v2.20.1

package-lock.json, packages/codegen-ui-react/package-lock.json, packages/codegen-ui/package-lock.json, packages/test-generator/package-lock.json
Security alerts have been raised and need to be addressed
run `npm audit fix` locally to address alerts
GitHub issue:
=> chore: apply updates from npm audit

package-lock.json, package.json, packages/codegen-ui-react/package-lock.json, packages/codegen-ui-react/package.json, packages/codegen-ui/package-lock.json, packages/codegen-ui/package.json, packages/test-generator/package-lock.json, packages/test-generator/package.json
Several dependabot alerts for `form-data` across the repo like https://github.com/aws-amplify/amplify-codegen-ui/security/dependabot/235
Set overrides for `form-data`.
Results from `npm run test:ci`:
```sh
➜  amplify-codegen-ui git:(form-data) nr test:ci   
> @aws-amplify/amplify-codegen-ui@0.1.0 test:ci
> lerna run test:ci --stream
lerna notice cli v6.4.1
lerna notice filter excluding "integration-test"
lerna info filter [ '!integration-test' ]
>  Lerna (powered by Nx)   Running target test:ci for 2 projects:
- @aws-amplify/codegen-ui-react
- @aws-amplify/codegen-ui
————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
> @aws-amplify/codegen-ui:"test:ci"
@aws-amplify/codegen-ui: > …
```
=> chore: set resolution for form-data
